# ----------------------------------------
# Version: 1.0.0 – tappaas PVE VM Template (manual-install entry point)
# State: Released
# Date: 2025-10-16
# Author: Erik, Lars (Tappaas)
# Purpose:
#     configuration.nix for the MANUAL NixOS install path: boot the NixOS
#     installer ISO, install a minimal system (which generates
#     hardware-configuration.nix), then drop this file in as
#     /etc/nixos/configuration.nix and `nixos-rebuild switch`.
#
#     All the actual TAPPaaS baseline lives in ./tappaas-common.nix so the very
#     same configuration can be baked into the prebuilt image (see flake.nix),
#     where the image format — not hardware-configuration.nix — provides the
#     disk, filesystem and bootloader device.
#
#     Help is available in the configuration.nix(5) man page, on
#     https://search.nixos.org/options and in the NixOS manual (`nixos-help`).
# ----------------------------------------

{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ # Machine-specific disk/boot layout generated by the NixOS installer.
      ./hardware-configuration.nix
      # The hardware-agnostic TAPPaaS baseline (shared with the prebuilt image).
      ./tappaas-common.nix
    ];
}
