#!/usr/bin/env bash
# TAPPaaS Module: coturn — Installation
#
# coturn TURN/STUN server for Nextcloud Talk WebRTC audio/video calls.
#
# Creates the coturn VM in Proxmox and applies initial configuration.
# It assumes that you are in the install directory.
#
# Secret planes:
#   Runtime:    /etc/secrets/coturn.env on the coturn VM (generated by NixOS on first boot)
#   Management: /home/tappaas/secrets/coturn.env on tappaas-cicd (written here at install time)
#
# Usage: ./install.sh <vmname>
# Example: ./install.sh coturn

set -euo pipefail

. /home/tappaas/bin/common-install-routines.sh

# Config-derived host — read from the loaded config ($JSON, keyed on $1), never a
# relative/literal file. Never hardcode the zone (modules deploy to dmz, etc.).
COTURN_HOST="$(get_config_value vmname coturn).$(get_config_value zone0 dmz).internal"
readonly MGMT_SECRETS="/home/tappaas/secrets/coturn.env"

# ── Nextcloud connector — owned by Nextcloud, NOT here (ADR-COM-0002) ─────────
# coturn does ONLY its own layer. The Talk TURN connector (sharing COTURN_SECRET
# with Nextcloud) is wired by NEXTCLOUD's services/nextcloud/install-service.sh,
# triggered by this module's config["nextcloud:fileservice"].connector = "talk".
# No cross-VM SSH push from this module. (N4 generalization for talk/hpb: follow-up.)

# ── Auto-detect WAN IP → write to coturn VM + management plane ───────────────
echo ""
info "${BOLD}Detecting WAN IP from OPNsense…${CL}"

CRED_FILE="/home/tappaas/.opnsense-credentials.txt"
FIREWALL="firewall.mgmt.internal"
WAN_IP=""

if [[ -f "$CRED_FILE" ]]; then
    OPNSENSE_TOKEN=$(sed -n '1p' "$CRED_FILE")
    OPNSENSE_SECRET=$(sed -n '2p' "$CRED_FILE")

    WAN_IP=$(curl -sk --max-time 10 \
        -u "${OPNSENSE_TOKEN}:${OPNSENSE_SECRET}" \
        "https://${FIREWALL}/api/interfaces/overview/interfacesInfo" \
        | jq -r '.rows[] | select(.identifier == "wan") | .ipv4 // empty' \
        | cut -d/ -f1 || true)
fi

if [[ -n "${WAN_IP}" ]]; then
    info "  Detected WAN IP: ${WAN_IP}"
    info "  Writing COTURN_EXTERNAL_IP to coturn VM…"
    ssh -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=no "tappaas@${COTURN_HOST}" \
        "sudo sed -i 's/^COTURN_EXTERNAL_IP=.*/COTURN_EXTERNAL_IP=${WAN_IP}/' /etc/secrets/coturn.env && \
         sudo systemctl restart coturn.service" && \
        info "  COTURN_EXTERNAL_IP=${WAN_IP} set and coturn restarted." || \
        warn "  Failed to update COTURN_EXTERNAL_IP on coturn VM — set it manually."
    # inline upsert (the toolbox has no upsert_secret)
    mkdir -p "$(dirname "${MGMT_SECRETS}")"
    { grep -v '^COTURN_EXTERNAL_IP=' "${MGMT_SECRETS}" 2>/dev/null || true; printf 'COTURN_EXTERNAL_IP=%s\n' "${WAN_IP}"; } > "${MGMT_SECRETS}.tmp"
    mv "${MGMT_SECRETS}.tmp" "${MGMT_SECRETS}"
    info "  COTURN_EXTERNAL_IP saved to management plane."
else
    warn "  Could not detect WAN IP from OPNsense — set it manually:"
    warn "    ssh tappaas@${COTURN_HOST}"
    warn "    sudo sed -i 's/COTURN_EXTERNAL_IP=/COTURN_EXTERNAL_IP=<YOUR-WAN-IP>/' /etc/secrets/coturn.env"
    warn "    sudo systemctl restart coturn.service"
fi

# ── Read COTURN_SECRET from the coturn VM → management plane ──────────────────
# Consumers that share the TURN shared-secret (nextcloud-hpb, and Nextcloud Talk)
# read COTURN_SECRET from the management plane — they have no SSH path to the
# coturn VM. The secret is generated by NixOS on first boot; read it once here and
# upsert it into the management-plane env. Runs unconditionally (independent of the
# WAN-IP detection above), since hpb's install will die without it.
echo ""
info "${BOLD}Reading COTURN_SECRET from coturn VM…${CL}"
COTURN_SECRET=$(ssh -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=accept-new \
    "tappaas@${COTURN_HOST}" \
    "sudo grep -h '^COTURN_SECRET=' /etc/secrets/coturn.env 2>/dev/null | cut -d= -f2-" 2>/dev/null || true)
if [[ -n "${COTURN_SECRET}" ]]; then
    # inline upsert (the toolbox has no upsert_secret); preserve any other keys
    mkdir -p "$(dirname "${MGMT_SECRETS}")"
    { grep -v '^COTURN_SECRET=' "${MGMT_SECRETS}" 2>/dev/null || true; printf 'COTURN_SECRET=%s\n' "${COTURN_SECRET}"; } > "${MGMT_SECRETS}.tmp"
    mv "${MGMT_SECRETS}.tmp" "${MGMT_SECRETS}"
    chmod 600 "${MGMT_SECRETS}"
    info "  COTURN_SECRET saved to management plane (${MGMT_SECRETS})."
else
    die "Could not read COTURN_SECRET from ${COTURN_HOST}:/etc/secrets/coturn.env — NixOS first-boot secret generation may not have completed."
fi

# ── Remaining manual steps ────────────────────────────────────────────────────
echo ""
warn "Ensure OPNsense has the following (not configured automatically):"
warn "  - NAT rule: WAN:3478 (UDP+TCP) -> coturn DMZ IP:3478"
warn "  - NAT rule: WAN:49152-65535 (UDP) -> coturn DMZ IP:49152-65535"
warn "  - DNS A record: $(get_config_value publicDomain '') -> public WAN IP"

echo ""
info "${GN}✓${CL} coturn installation completed successfully."
