#!/usr/bin/env bash
# TAPPaaS Module: coturn — Installation
#
# coturn TURN/STUN server for Nextcloud Talk WebRTC audio/video calls.
#
# Creates the coturn VM in Proxmox and applies initial configuration.
# It assumes that you are in the install directory.
#
# Secret planes:
#   Runtime:    /etc/secrets/coturn.env on the coturn VM (generated by NixOS on first boot)
#   Management: /home/tappaas/secrets/coturn.env on tappaas-cicd (written here at install time)
#
# Usage: ./install.sh <vmname>
# Example: ./install.sh coturn

set -euo pipefail

. /home/tappaas/bin/common-install-routines.sh

# Config-derived host — read from the loaded config ($JSON, keyed on $1), never a
# relative/literal file. Never hardcode the zone (modules deploy to dmz, etc.).
COTURN_HOST="$(get_config_value vmname coturn).$(get_config_value zone0 dmz).internal"
readonly MGMT_SECRETS="/home/tappaas/secrets/coturn.env"

# Recreate-safe SSH: a redeployed VM (same hostname, new host key) trips strict
# host-key checking, so the ssh calls below (which use accept-new — it accepts
# unknown hosts but REJECTS changed keys) fail on a delete+reinstall and the
# secret read never succeeds. Clear any stale key so accept-new re-pins the
# current one (mirrors nextcloud-hpb's install.sh).
ssh-keygen -R "${COTURN_HOST}" >/dev/null 2>&1 || true

# ── Nextcloud connector — owned by Nextcloud, NOT here (ADR-COM-0002) ─────────
# coturn does ONLY its own layer. The Talk TURN connector (sharing COTURN_SECRET
# with Nextcloud) is wired by NEXTCLOUD's services/nextcloud/install-service.sh,
# triggered by this module's config["nextcloud:fileservice"].connector = "talk".
# No cross-VM SSH push from this module. (N4 generalization for talk/hpb: follow-up.)

# ── Detect the public (WAN/NAT) IP coturn advertises as external-ip ───────────
# Detected from the coturn VM itself via external echo services — the post-NAT IP
# the outside world sees, which is exactly what TURN external-ip needs. Cred-free
# and robust to OPNsense API / interface-naming changes (the prior OPNsense
# interfacesInfo query was fragile: it failed silently here, leaving external Talk
# media broken while the install still reported success). Single-WAN assumption;
# requires DMZ egress to the internet. Falls back to a manual warning if blocked.
echo ""
info "${BOLD}Detecting public IP from the coturn VM…${CL}"
# Retry across providers AND rounds — a single curl can miss transiently even
# when egress is healthy (declarative wait, like the secret read below).
WAN_IP=$(ssh -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=accept-new \
    "tappaas@${COTURN_HOST}" '
    for _round in $(seq 1 6); do
        for u in https://checkip.amazonaws.com https://api.ipify.org https://ifconfig.me/ip; do
            ip=$(curl -s --max-time 6 "$u" 2>/dev/null | tr -dc "0-9.")
            if [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then echo "$ip"; exit 0; fi
        done
        sleep 5
    done' 2>/dev/null || true)

if [[ -n "${WAN_IP}" ]]; then
    info "  Detected public IP: ${WAN_IP}"
    ssh -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=accept-new "tappaas@${COTURN_HOST}" \
        "sudo sed -i 's/^COTURN_EXTERNAL_IP=.*/COTURN_EXTERNAL_IP=${WAN_IP}/' /etc/secrets/coturn.env && \
         sudo systemctl restart coturn.service" && \
        info "  COTURN_EXTERNAL_IP=${WAN_IP} set and coturn restarted." || \
        warn "  Failed to update COTURN_EXTERNAL_IP on coturn VM — set it manually."
    # inline upsert (the toolbox has no upsert_secret)
    mkdir -p "$(dirname "${MGMT_SECRETS}")"
    { grep -v '^COTURN_EXTERNAL_IP=' "${MGMT_SECRETS}" 2>/dev/null || true; printf 'COTURN_EXTERNAL_IP=%s\n' "${WAN_IP}"; } > "${MGMT_SECRETS}.tmp"
    mv "${MGMT_SECRETS}.tmp" "${MGMT_SECRETS}"
    info "  COTURN_EXTERNAL_IP saved to management plane."
else
    warn "  Could not detect public IP from the coturn VM (DMZ egress blocked?) — external Talk media will fail until set manually:"
    warn "    ssh tappaas@${COTURN_HOST}"
    warn "    sudo sed -i 's/^COTURN_EXTERNAL_IP=.*/COTURN_EXTERNAL_IP=<YOUR-WAN-IP>/' /etc/secrets/coturn.env"
    warn "    sudo systemctl restart coturn.service"
fi

# ── Read COTURN_SECRET from the coturn VM → management plane ──────────────────
# Consumers that share the TURN shared-secret (nextcloud-hpb, and Nextcloud Talk)
# read COTURN_SECRET from the management plane — they have no SSH path to the
# coturn VM. The secret is generated by NixOS on first boot; read it once here and
# upsert it into the management-plane env. Runs unconditionally (independent of the
# WAN-IP detection above), since hpb's install will die without it.
echo ""
info "${BOLD}Reading COTURN_SECRET from coturn VM…${CL}"
# NixOS first-boot generates the secret asynchronously; poll for it (idempotent —
# a re-run just re-reads) instead of failing on a fresh-VM startup race.
COTURN_SECRET=""
for _attempt in $(seq 1 30); do
    COTURN_SECRET=$(ssh -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=accept-new \
        "tappaas@${COTURN_HOST}" \
        "sudo grep -h '^COTURN_SECRET=' /etc/secrets/coturn.env 2>/dev/null | cut -d= -f2-" 2>/dev/null || true)
    [[ -n "${COTURN_SECRET}" ]] && break
    [[ "${_attempt}" -eq 1 ]] && info "  Secret not present yet — waiting for first-boot generation (up to ~5min)…"
    sleep 10
done
if [[ -n "${COTURN_SECRET}" ]]; then
    # inline upsert (the toolbox has no upsert_secret); preserve any other keys
    mkdir -p "$(dirname "${MGMT_SECRETS}")"
    { grep -v '^COTURN_SECRET=' "${MGMT_SECRETS}" 2>/dev/null || true; printf 'COTURN_SECRET=%s\n' "${COTURN_SECRET}"; } > "${MGMT_SECRETS}.tmp"
    mv "${MGMT_SECRETS}.tmp" "${MGMT_SECRETS}"
    chmod 600 "${MGMT_SECRETS}"
    info "  COTURN_SECRET saved to management plane (${MGMT_SECRETS})."
else
    die "Could not read COTURN_SECRET from ${COTURN_HOST}:/etc/secrets/coturn.env — NixOS first-boot secret generation may not have completed."
fi

# ── Remaining manual steps ────────────────────────────────────────────────────
echo ""
warn "Ensure OPNsense has the following (not configured automatically):"
warn "  - NAT rule: WAN:3478 (UDP+TCP) -> coturn DMZ IP:3478"
warn "  - NAT rule: WAN:49152-65535 (UDP) -> coturn DMZ IP:49152-65535"
warn "  - DNS A record: $(get_config_value publicDomain '') -> public WAN IP"

echo ""
info "${GN}✓${CL} coturn installation completed successfully."
