#!/usr/bin/env bash
#
# install tappass-cicd foundation in a barebone nixos vm

# Strict mode: exit on error, undefined vars, pipe failures
set -euo pipefail

# Helper functions for output.
# This runs over SSH from install-platform.sh, so keep the console quiet:
# bootstrap's own status lines go to [Debug] (shown only when TAPPAAS_DEBUG=1),
# the noisy git/keygen output is redirected to $BOOTSTRAP_LOG, and the
# nixos-rebuild output is rendered as a row of progress dots (one per line).
BOOTSTRAP_LOG="${BOOTSTRAP_LOG:-/tmp/tappaas-bootstrap.log}"
: >"$BOOTSTRAP_LOG" 2>/dev/null || BOOTSTRAP_LOG=/dev/null
msg_info() { if [ "${TAPPAAS_DEBUG:-0}" = "1" ]; then echo "DEBUG: $*"; fi; }
msg_ok()   { if [ "${TAPPAAS_DEBUG:-0}" = "1" ]; then echo "DEBUG: $*"; fi; }

# Find the repo version of TAPPaaS to use
msg_info "Determining TAPPaaS repo to use"
if [ -z "${1:-}" ]; then
  REPOTOCLONE="https://codeberg.org/TAPPaaS/TAPPaaS.git"
else
  REPOTOCLONE="$1"
fi
msg_ok "Determined TAPPaaS repo to use: ${REPOTOCLONE}"

# Find the branch version of TAPPaaS to use
msg_info "Determining TAPPaaS branch to use"
if [ -z "${2:-}" ]; then
  BRANCH="stable"
else
  BRANCH="$2"
fi
msg_ok "Determined TAPPaaS branch to use: ${BRANCH}"

# clone the tappaas-cicd repo (idempotent: reuse an existing checkout so this
# script can be safely re-run, e.g. by install-platform.sh's Phase B retry).
if [ -d TAPPaaS/.git ]; then
  msg_info "TAPPaaS already cloned — reusing existing checkout"
else
  msg_info "Cloning TAPPaaS repository $REPOTOCLONE ..."
  git clone "$REPOTOCLONE" >>"$BOOTSTRAP_LOG" 2>&1
fi
msg_info "switching to branch $BRANCH..."
cd TAPPaaS || exit 1
# Force the switch: a reused checkout may carry working-tree changes that block a
# branch switch — notably nix `result` build-output symlinks regenerated by
# pre-update.sh (some were committed before being .gitignored). They are
# regenerable, so discarding local changes here is safe.
git checkout -f "$BRANCH" >>"$BOOTSTRAP_LOG" 2>&1 || git checkout "$BRANCH" >>"$BOOTSTRAP_LOG" 2>&1
git pull --ff-only >>"$BOOTSTRAP_LOG" 2>&1 || true

# go to the tappaas-cicd folder
msg_info "Changing to TAPPaaS-CICD directory and rebuilding the NixOS configuration..."
cd src/foundation/tappaas-cicd || exit 1

# The cicd VM is cloned from the PREBUILT NixOS template image, which has no
# /etc/nixos/hardware-configuration.nix (the image was built declaratively, not
# via the NixOS installer). tappaas-cicd.nix imports that file for the machine's
# real disk/boot layout, so generate it now from the running hardware. (Use
# --show-hardware-config so we write only hardware-configuration.nix and never
# touch configuration.nix — the system is built from the flake regardless.)
if [ ! -f /etc/nixos/hardware-configuration.nix ]; then
  msg_info "Generating /etc/nixos/hardware-configuration.nix from running hardware"
  sudo mkdir -p /etc/nixos
  sudo nixos-generate-config --show-hardware-config 2>>"$BOOTSTRAP_LOG" | sudo tee /etc/nixos/hardware-configuration.nix >/dev/null 2>>"$BOOTSTRAP_LOG"
  msg_ok "Generated /etc/nixos/hardware-configuration.nix"
fi

# rebuild the nixos configuration. NixOS version is pinned in ./flake.lock
# (declared in git); --impure only to read /etc/nixos/hardware-configuration.nix.
# The very verbose build output is rendered as a row of progress dots (one per
# line) and captured in full to $BOOTSTRAP_LOG; on failure its tail is shown.
msg_info "Rebuilding NixOS (nixos-rebuild switch) — progress dots follow"
if sudo nixos-rebuild switch --flake .#tappaas-cicd --impure 2>&1 \
     | tee -a "$BOOTSTRAP_LOG" \
     | { while IFS= read -r _; do printf '.'; done; printf '\n'; }; then
  msg_ok "NixOS rebuild complete"
else
  echo "ERROR: nixos-rebuild switch failed — tail of ${BOOTSTRAP_LOG}:" >&2
  tail -n 40 "$BOOTSTRAP_LOG" >&2
  exit 1
fi

# create ssh keys for the tappaas user (idempotent: keep an existing keypair).
msg_info "Creating SSH keys for the tappaas user and installing them for the proxmox host..."
if [ ! -f /home/tappaas/.ssh/id_ed25519 ]; then
  ssh-keygen -t ed25519 -f /home/tappaas/.ssh/id_ed25519 -N "" -C "tappaas-cicd" >>"$BOOTSTRAP_LOG" 2>&1
fi
# enforce secure permissions on the private key
sudo chown tappaas:users /home/tappaas/.ssh/id_ed25519*
sudo chmod 600 /home/tappaas/.ssh/id_ed25519
# add the public key to authorized_keys so that tappaas user can ssh to itself
# (idempotent: only append if not already present).
touch /home/tappaas/.ssh/authorized_keys
grep -qxF "$(cat /home/tappaas/.ssh/id_ed25519.pub)" /home/tappaas/.ssh/authorized_keys \
  || cat /home/tappaas/.ssh/id_ed25519.pub >> /home/tappaas/.ssh/authorized_keys
chmod 600 /home/tappaas/.ssh/authorized_keys

chmod +x /home/tappaas/TAPPaaS/src/foundation/tappaas-cicd/bootstrap.sh
chmod +x /home/tappaas/TAPPaaS/src/foundation/tappaas-cicd/install.sh

msg_info "Please reboot tappaas-cicd VM."