#!/usr/bin/env bash
# TAPPaaS Firewall Module Update
#
# Updates the OPNsense firewall software via SSH and applies zone configuration.
#
# When firewallType is "NONE" (no OPNsense deployed), this script skips all
# OPNsense-specific operations and prints a reminder.
#
# Note: Connectivity checks (ping, SSH) are handled by update-module.sh
# via the pre-update test-module.sh call before this script runs.
#
# Note: OPNsense presents a menu when logging in interactively (option 8 = shell).
# When SSH is used with a command argument, it bypasses the menu and runs directly.

set -euo pipefail

. /home/tappaas/bin/common-install-routines.sh

readonly CONFIG_DIR="/home/tappaas/config"
readonly FIREWALL_JSON="${CONFIG_DIR}/firewall.json"
FIREWALL_FQDN="firewall.mgmt.internal"

# ── Check firewallType ───────────────────────────────────────────────

FIREWALL_TYPE="opnsense"
if [[ -f "${FIREWALL_JSON}" ]]; then
    FIREWALL_TYPE=$(jq -r '.firewallType // "opnsense"' "${FIREWALL_JSON}")
fi

if [[ "${FIREWALL_TYPE}" == "NONE" ]]; then
    warn "firewallType=NONE — OPNsense is not managed by TAPPaaS."
    warn "Skipping firewall update. Manage your firewall manually."
    exit 0
fi

# ── Apply zone configuration ────────────────────────────────────────

info "Applying zone configuration..."
/home/tappaas/bin/zone-manager --no-ssl-verify --zones-file /home/tappaas/config/zones.json --execute

# When zone-manager creates new opt interfaces (e.g. activating test1/test2),
# OPNsense's auto-generated anti-lockout and bootp pass rules for those
# interfaces are NOT regenerated by /api/firewall/filter/apply. Without those
# rules, DHCP DISCOVER from a fresh VM is silently dropped on the new VLAN.
# `configctl filter reload` re-renders the full ruleset, including auto rules.
info "Reloading OPNsense filter to regenerate auto-rules for any new interfaces..."
ssh root@"$FIREWALL_FQDN" "configctl filter reload" >/dev/null 2>&1 \
    || warn "configctl filter reload returned non-zero (continuing)"

# ── Sync OPNsense VM trunks with active VLAN zones ──────────────────
#
# The OPNsense VM's Proxmox net0 trunks list controls which VLAN tags the
# host's vlan-aware bridge will forward to the VM. The list is set ONCE at
# VM creation from firewall.json's trunks0 field — never updated. Activating
# a new zone afterwards (e.g. test1/test2 for regression testing) requires
# the OPNsense VM to also receive that VLAN. Without this step:
#   - The new VLAN interface (vlan0.<tag>) exists on OPNsense and dnsmasq
#     happily listens, but Proxmox's bridge drops the VM's tagged frames
#     because the VLAN isn't in the OPNsense NIC's trunk allowlist.
#   - DHCP DISCOVER never reaches OPNsense; VMs in the new zone get no IP.
# This re-resolves the trunks0 list against the current zones.json (skipping
# Inactive zones, same logic as Create-TAPPaaS-VM.sh::resolve_trunks) and
# applies the result via `qm set` on the node hosting the firewall VM.

info "Syncing OPNsense VM trunks with active VLAN zones..."

FIREWALL_VMID=$(jq -r '.vmid // empty' "${FIREWALL_JSON}")
FIREWALL_MAC=$(jq -r '.mac0 // empty' "${FIREWALL_JSON}")
FIREWALL_BRIDGE=$(jq -r '.bridge0 // "lan"' "${FIREWALL_JSON}")
TRUNK_ZONES=$(jq -r '.trunks0 // ""' "${FIREWALL_JSON}")

# Find the cluster node currently hosting the firewall VM (firewall.json has
# no static .node field — its location can change via HA migration).
PRIMARY_NODE=$(get_primary_node_fqdn 2>/dev/null || echo "tappaas1.mgmt.internal")
FIREWALL_NODE=$(ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
                    root@"${PRIMARY_NODE}" \
                    "pvesh get /cluster/resources --type vm --output-format json 2>/dev/null \
                     | jq -r --arg vmid \"${FIREWALL_VMID}\" '.[] | select(.vmid==(\$vmid|tonumber)) | .node'" \
                    2>/dev/null | head -1)
# If MAC is not in firewall.json, read it live from the running VM
if [[ -z "${FIREWALL_MAC}" && -n "${FIREWALL_NODE}" && -n "${FIREWALL_VMID}" ]]; then
    FIREWALL_MAC=$(ssh -o BatchMode=yes root@"${FIREWALL_NODE}.mgmt.internal" \
                    "qm config ${FIREWALL_VMID}" 2>/dev/null \
                    | grep -E '^net0:' \
                    | grep -oE '[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){5}' \
                    | head -1)
fi

if [[ -z "${FIREWALL_NODE}" || -z "${FIREWALL_VMID}" || -z "${TRUNK_ZONES}" || -z "${FIREWALL_MAC}" ]]; then
    warn "  Missing node/vmid/mac/trunks0 — skipping trunk sync (node=${FIREWALL_NODE}, vmid=${FIREWALL_VMID}, mac=${FIREWALL_MAC})"
else
    # Resolve zone names → comma-separated VLAN tags, skipping Inactive zones
    TRUNK_TAGS=$(jq -r --arg zlist "${TRUNK_ZONES}" '
        ($zlist | split(";")) as $names
        | [ $names[]
            | . as $n
            | (.. | select(type == "object")) as $zones | empty
          ]
        ' "${CONFIG_DIR}/zones.json" 2>/dev/null || true)
    # Simpler, more robust extraction:
    TRUNK_TAGS=""
    IFS=';' read -ra _names <<< "${TRUNK_ZONES}"
    for zone_name in "${_names[@]}"; do
        state=$(jq -r --arg n "${zone_name}" '.[$n].state // empty' "${CONFIG_DIR}/zones.json")
        if [[ "${state}" == "Active" || "${state}" == "Mandatory" ]]; then
            tag=$(jq -r --arg n "${zone_name}" '.[$n].vlantag // empty' "${CONFIG_DIR}/zones.json")
            if [[ -n "${tag}" && "${tag}" != "0" ]]; then
                if [[ -z "${TRUNK_TAGS}" ]]; then
                    TRUNK_TAGS="${tag}"
                else
                    TRUNK_TAGS="${TRUNK_TAGS};${tag}"
                fi
            fi
        elif [[ -n "${state}" ]]; then
            info "  Skipping trunk zone '${zone_name}' (state=${state})"
        else
            warn "  Trunk zone '${zone_name}' not found in zones.json — skipping"
        fi
    done

    if [[ -z "${TRUNK_TAGS}" ]]; then
        warn "  No active VLAN trunks to configure on OPNsense VM"
    else
        FIREWALL_NODE_FQDN="${FIREWALL_NODE}.mgmt.internal"
        NET0_OPTS="virtio=${FIREWALL_MAC},bridge=${FIREWALL_BRIDGE},trunks=${TRUNK_TAGS}"
        info "  Setting net0 on VM ${FIREWALL_VMID} (node ${FIREWALL_NODE}): trunks=${TRUNK_TAGS}"
        # Single-quote the value so semicolons in trunks=... aren't interpreted
        # as command separators by the remote shell.
        if ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
                root@"${FIREWALL_NODE_FQDN}" \
                "qm set ${FIREWALL_VMID} --net0 '${NET0_OPTS}'" >/dev/null 2>&1; then
            info "  ${GN}✓${CL} OPNsense VM trunks synced"
        else
            warn "  Failed to update OPNsense VM trunks — new VLANs may not receive traffic"
        fi
    fi
fi

# ── OPNsense update ─────────────────────────────────────────────────

info "Updating OPNsense (base, kernel, and packages)..."
if [[ "${OPT_DEBUG:-0}" -eq 1 ]]; then
    ssh root@"$FIREWALL_FQDN" "opnsense-update -bkp" || {
        warn "OPNsense update returned non-zero exit code"
    }
else
    ssh root@"$FIREWALL_FQDN" "opnsense-update -bkp" 2>&1 | while IFS= read -r _; do
        printf "."
    done || {
        echo ""
        warn "OPNsense update returned non-zero exit code"
    }
    echo ""
fi

# ── Check if reboot is required ─────────────────────────────────────

info "Checking if reboot is required..."
RUNNING_KERNEL=$(ssh root@"$FIREWALL_FQDN" "uname -r")
INSTALLED_KERNEL=$(ssh root@"$FIREWALL_FQDN" "freebsd-version -k")

if [[ "$RUNNING_KERNEL" != "$INSTALLED_KERNEL" ]]; then
    warn "Firewall reboot is required to complete the update"
    warn "  Running kernel:   $RUNNING_KERNEL"
    warn "  Installed kernel: $INSTALLED_KERNEL"
    warn "Please schedule a maintenance window to reboot the firewall"
else
    info "No reboot required"
fi

info "${GN}✓${CL} Firewall update completed"
