#!/usr/bin/env bash
# TAPPaaS Firewall Module Update
#
# Updates the OPNsense firewall software via SSH and applies zone configuration.
#
# Order of operations:
# 1. OPNsense software update (base, kernel, packages)
# 2. Unconditional reboot to apply updates and regenerate configs
# 3. Wait for firewall to come back online
# 4. Verify DNS is working (Unbound health check)
# 5. Apply zone configuration via zone-manager
# 6. Remaining configuration (proxy, net0 trunks, etc.)
#
# This order ensures OPNsense updates are applied BEFORE zone-manager runs,
# which triggers Unbound config regeneration. See ISSUES.md for background.
#
# When firewallType is "NONE" (no OPNsense deployed), this script skips all
# OPNsense-specific operations and prints a reminder.
#
# Note: Connectivity checks (ping, SSH) are handled by update-module.sh
# via the pre-update test-module.sh call before this script runs.
#
# Note: OPNsense presents a menu when logging in interactively (option 8 = shell).
# When SSH is used with a command argument, it bypasses the menu and runs directly.

set -euo pipefail

. /home/tappaas/bin/common-install-routines.sh

readonly CONFIG_DIR="/home/tappaas/config"
readonly FIREWALL_JSON="${CONFIG_DIR}/firewall.json"
FIREWALL_FQDN="firewall.mgmt.internal"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR

# ── Check firewallType ───────────────────────────────────────────────

FIREWALL_TYPE="opnsense"
if [[ -f "${FIREWALL_JSON}" ]]; then
    FIREWALL_TYPE=$(jq -r '.firewallType // "opnsense"' "${FIREWALL_JSON}")
fi

if [[ "${FIREWALL_TYPE}" == "NONE" ]]; then
    warn "firewallType=NONE — OPNsense is not managed by TAPPaaS."
    warn "Skipping firewall update. Manage your firewall manually."
    exit 0
fi

# ── OPNsense update ─────────────────────────────────────────────────
#
# Run OPNsense update FIRST, before zone-manager. This ensures any
# package updates (including potential dnspython/unbound fixes) are
# applied before we trigger config regeneration via zone-manager.

info "Updating OPNsense (base, kernel, and packages)..."
if [[ "${OPT_DEBUG:-0}" -eq 1 ]]; then
    ssh root@"$FIREWALL_FQDN" "opnsense-update -bkp" || {
        warn "OPNsense update returned non-zero exit code"
    }
else
    ssh root@"$FIREWALL_FQDN" "opnsense-update -bkp" 2>&1 | while IFS= read -r _; do
        printf "."
    done || {
        echo ""
        warn "OPNsense update returned non-zero exit code"
    }
    echo ""
fi

# ── Reboot firewall (unconditional) ─────────────────────────────────
#
# Always reboot after OPNsense update during the install/update phase.
# This ensures:
# - Any kernel updates are applied
# - Unbound config is regenerated with current OPNsense state
# - We catch any Unbound/DNSBL issues BEFORE zone-manager runs
#
# The reboot also serves as a clean slate for zone configuration.

info "Rebooting firewall to apply updates..."
ssh root@"$FIREWALL_FQDN" "shutdown -r now" 2>/dev/null || true

# Wait for SSH to go down (firewall is rebooting)
info "Waiting for firewall to reboot..."
sleep 10

# Wait for SSH to come back (max 5 minutes)
WAIT_MAX=300
WAIT_COUNT=0
while ! ssh -o ConnectTimeout=5 -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
        root@"$FIREWALL_FQDN" "echo ok" >/dev/null 2>&1; do
    sleep 5
    WAIT_COUNT=$((WAIT_COUNT + 5))
    if [[ $WAIT_COUNT -ge $WAIT_MAX ]]; then
        error "Firewall did not come back after reboot within ${WAIT_MAX}s"
        exit 1
    fi
    printf "."
done
echo ""
info "${GN}✓${CL} Firewall is back online"

# ── Verify Unbound DNS is working ────────────────────────────────────
#
# After reboot, OPNsense regenerates Unbound config. If there's a
# Python/dnspython version mismatch (see ISSUES.md), Unbound may fail
# to start. We check DNS here to catch the problem early.

info "Verifying Unbound DNS is responding..."
DNS_CHECK_RETRIES=6
DNS_CHECK_COUNT=0
while ! dig @10.0.0.1 firewall.mgmt.internal +short +timeout=5 >/dev/null 2>&1; do
    DNS_CHECK_COUNT=$((DNS_CHECK_COUNT + 1))
    if [[ $DNS_CHECK_COUNT -ge $DNS_CHECK_RETRIES ]]; then
        warn "Unbound DNS not responding on 10.0.0.1 after ${DNS_CHECK_RETRIES} attempts"
        warn "This may indicate a Python/dnspython version mismatch in OPNsense."
        warn "See src/foundation/firewall/ISSUES.md for recovery steps."
        warn "Attempting to continue, but zone-manager may fail..."
        break
    fi
    sleep 5
    printf "."
done
if [[ $DNS_CHECK_COUNT -lt $DNS_CHECK_RETRIES ]]; then
    echo ""
    info "${GN}✓${CL} Unbound DNS is responding"
fi

# ── Apply zone configuration ────────────────────────────────────────

info "Applying zone configuration..."
/home/tappaas/bin/zone-manager --no-ssl-verify --zones-file /home/tappaas/config/zones.json --execute

# When zone-manager creates new opt interfaces (e.g. activating testAllowA/testAllowB),
# OPNsense's auto-generated anti-lockout and bootp pass rules for those
# interfaces are NOT regenerated by /api/firewall/filter/apply. Without those
# rules, DHCP DISCOVER from a fresh VM is silently dropped on the new VLAN.
# `configctl filter reload` re-renders the full ruleset, including auto rules.
info "Reloading OPNsense filter to regenerate auto-rules for any new interfaces..."
ssh root@"$FIREWALL_FQDN" "configctl filter reload" >/dev/null 2>&1 \
    || warn "configctl filter reload returned non-zero (continuing)"

# Compile-check the generated ruleset (#307). OPNsense renders the active filter
# spec to /tmp/rules.debug; `pfctl -nf` parses it WITHOUT loading, so a non-zero
# rc means the ruleset is broken (a malformed rule a reload accepted silently).
# Fail the update here so the deploy stops (and update-module.sh rolls the
# firewall snapshot back) before a broken ruleset is declared healthy.
# Reachability note: the firewall is addressed by FQDN, kept DNS-independent via
# the cicd's static /etc/hosts pin (networking.hosts in tappaas-cicd.nix) so this
# check — and the rollback that may follow — work even if Unbound is down.
info "Compile-checking the firewall ruleset (pfctl -nf /tmp/rules.debug)..."
if ssh root@"$FIREWALL_FQDN" "pfctl -nf /tmp/rules.debug" >/dev/null 2>&1; then
    info "${GN}✓${CL} Firewall ruleset compiles cleanly"
else
    error "pfctl ruleset compile-check FAILED — /tmp/rules.debug does not parse."
    error "The firewall ruleset is broken; aborting the update (deploy should roll back)."
    exit 1
fi

# ── Reconcile the firewall's own reverse-proxy entry ────────────────
#
# The firewall is installed in two phases: a bare OPNsense install, then a
# full update once tappaas-cicd exists. The proxy entry that exposes the
# OPNsense GUI (e.g. firewall.<domain>, mgmt-restricted, DNS-01 cert) can only
# be created in the second phase, because it needs caddy-manager and the
# os-caddy plugin — neither present during the bare install. We therefore
# reconcile it here on every update: firewall:proxy update-service is
# idempotent (creates the domain + handler if missing, re-applies the access
# list / upstream / TLS strategy otherwise), so this is a no-op once converged.
#
# Guarded on the firewall declaring firewall:proxy in its own dependsOn — i.e.
# the operator has opted the GUI in to the reverse proxy. The proxy details
# (proxyDomain, proxyPort, proxyUpstreamTls, proxyTls, proxyAllowedZones) are
# read from firewall.json by the service script itself.
if jq -e '(.dependsOn // []) | index("firewall:proxy")' "${FIREWALL_JSON}" >/dev/null 2>&1; then
    info "Reconciling the firewall's own reverse-proxy entry (firewall:proxy)..."
    if [[ -x "${SCRIPT_DIR}/services/proxy/update-service.sh" ]]; then
        "${SCRIPT_DIR}/services/proxy/update-service.sh" firewall \
            || warn "firewall:proxy update-service for the firewall returned non-zero (continuing)"
    else
        warn "  firewall:proxy update-service.sh not found — skipping self-proxy reconcile"
    fi
fi

# ── Sync OPNsense VM net0 trunks with active VLAN zones ─────────────
#
# The OPNsense VM's Proxmox net0 trunks list controls which VLAN tags the
# host's vlan-aware bridge forwards to the VM. It is set ONCE at VM creation
# and never updated, so a zone activated afterwards is unreachable: the
# vlan0.<tag> interface exists on OPNsense and dnsmasq listens, but Proxmox's
# bridge drops the VM's tagged frames (the VLAN isn't in the NIC's trunk
# allowlist) and DHCP DISCOVER never arrives. See #194.
#
# The trunk list is derived from ALL active zones in zones.json (firewall.json
# carries trunks0="ALL"), so new zones are picked up with no config edit. A
# trunks-only `qm set --net0` updates the bridge VLAN filter live, without
# recreating the NIC — safe on the running firewall.
#
# IMPORTANT: we deliberately do NOT change `queues` here. Changing queues on a
# running VM forces QEMU to hot-replug the virtio NIC, which drops OPNsense's
# LAN + all VLAN parent interfaces until a reboot (observed outage). queues is
# therefore set only at VM creation (Create-TAPPaaS-VM.sh); here we PRESERVE
# whatever queues value the live NIC already has.

info "Syncing OPNsense VM net0 trunks with active VLAN zones..."

# shellcheck source=../cluster/lib/vm-net.sh disable=SC1091
. /home/tappaas/TAPPaaS/src/foundation/cluster/lib/vm-net.sh

FIREWALL_VMID=$(jq -r '.vmid // empty' "${FIREWALL_JSON}")
FIREWALL_BRIDGE=$(jq -r '.bridge0 // "lan"' "${FIREWALL_JSON}")
FIREWALL_TRUNKS0=$(jq -r '.trunks0 // "ALL"' "${FIREWALL_JSON}")

# Find the cluster node currently hosting the firewall VM (its location can
# change via HA migration).
PRIMARY_NODE=$(get_primary_node_fqdn 2>/dev/null || echo "tappaas1.mgmt.internal")
FIREWALL_NODE=$(ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
                    root@"${PRIMARY_NODE}" \
                    "pvesh get /cluster/resources --type vm --output-format json 2>/dev/null \
                     | jq -r --arg vmid \"${FIREWALL_VMID}\" '.[] | select(.vmid==(\$vmid|tonumber)) | .node'" \
                    2>/dev/null | head -1)

DESIRED_TRUNKS=$(vmnet_resolve_trunks "${FIREWALL_TRUNKS0}" "${CONFIG_DIR}/zones.json")

if [[ -z "${FIREWALL_NODE}" || -z "${FIREWALL_VMID}" ]]; then
    warn "  Could not locate firewall VM (node=${FIREWALL_NODE}, vmid=${FIREWALL_VMID}) — skipping net0 sync"
elif [[ -z "${DESIRED_TRUNKS}" ]]; then
    warn "  No active VLAN trunks resolved from zones.json — skipping net0 sync"
else
    FIREWALL_NODE_FQDN="${FIREWALL_NODE}.mgmt.internal"
    LIVE_NET0=$(ssh -o BatchMode=yes root@"${FIREWALL_NODE_FQDN}" \
                    "qm config ${FIREWALL_VMID}" 2>/dev/null | awk -F': ' '/^net0:/ {print $2; exit}')

    LIVE_MAC=$(vmnet_parse "${LIVE_NET0}" mac)
    LIVE_TRUNKS=$(vmnet_parse "${LIVE_NET0}" trunks)
    LIVE_TAG=$(vmnet_parse "${LIVE_NET0}" tag)
    LIVE_QUEUES=$(vmnet_parse "${LIVE_NET0}" queues)

    if [[ -z "${LIVE_MAC}" ]]; then
        warn "  Could not read firewall net0 MAC — skipping net0 sync"
    elif [[ "${LIVE_TRUNKS}" == "${DESIRED_TRUNKS}" ]]; then
        info "  ${GN}✓${CL} net0 trunks already in sync (${DESIRED_TRUNKS})"
    else
        # Refresh trunks only; preserve MAC, tag and the existing queues value
        # (changing queues live would recreate the NIC — see note above).
        NET0_OPTS=$(vmnet_build_netopts "${FIREWALL_BRIDGE}" "${LIVE_MAC}" "${LIVE_TAG}" "${DESIRED_TRUNKS}" "${LIVE_QUEUES}")
        info "  Updating net0 trunks on VM ${FIREWALL_VMID} (node ${FIREWALL_NODE}):"
        info "    trunks: ${LIVE_TRUNKS:-none} → ${DESIRED_TRUNKS} (queues preserved: ${LIVE_QUEUES:-none})"
        # Single-quote the value so ';' in trunks=... is not a command separator.
        if ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
                root@"${FIREWALL_NODE_FQDN}" \
                "qm set ${FIREWALL_VMID} --net0 '${NET0_OPTS}'" >/dev/null 2>&1; then
            info "  ${GN}✓${CL} OPNsense VM net0 trunks synced"
        else
            warn "  Failed to update OPNsense VM net0 trunks — new VLANs may not receive traffic"
        fi
    fi
fi

info "${GN}✓${CL} Firewall update completed"
