#!/usr/bin/env bash
# Create-TAPPaaS-LXC.sh — TAPPaaS LXC creator with GPU passthrough
# Author: Erik Daniel007
#
# Path: bin/Create-TAPPaaS-LXC.sh
# Runs ON the Proxmox node (tappaas2), called via SSH from install-vm.sh

set -euo pipefail

YW="\033[33m"; RD="\033[01;31m"; GN="\033[1;92m"; CL="\033[m"; BOLD="\033[1m"

function error_handler() {
  echo -e "\n${RD}[ERROR]${CL} line $1: $2 (exit $?)"
  if pct status "$VMID" &>/dev/null; then
    pct stop "$VMID" &>/dev/null || true
    pct destroy "$VMID" &>/dev/null || true
  fi
}
trap 'error_handler $LINENO "$BASH_COMMAND"' ERR

# --- Args & JSON ---
[ -z "${1:-}" ] && { echo -e "${RD}[ERROR]${CL} Usage: $0 <vmname>"; exit 1; }
JSON_CONFIG="/root/tappaas/$1.json"
META_CONFIG="/root/tappaas/$1.meta.json"
[ -f "$JSON_CONFIG" ] || { echo -e "${RD}[ERROR]${CL} Not found: $JSON_CONFIG"; exit 1; }
[ -f "$META_CONFIG" ] || { echo -e "${RD}[ERROR]${CL} Not found: $META_CONFIG"; exit 1; }

JSON=$(cat "$JSON_CONFIG")
META=$(cat "$META_CONFIG")

get_val()  { echo "$JSON" | jq -r --arg k "$1" '.[$k] // $d' --arg d "${2:-}"; }
get_meta() { echo "$META" | jq -r "$1"; }

VMID=$(get_val vmid);           [ -z "$VMID" ] && { echo "Missing vmid"; exit 1; }
VMNAME=$(get_val vmname "$1")
CORES=$(get_val cores 16)
MEMORY=$(get_val memory 49152)
DISK=$(get_val diskSize 32G)
STORAGE=$(get_val storage local-lvm)
BRIDGE=$(get_val bridge0 lan)
VMTAG=$(get_val vmtag "ai")

KFD_MAJOR=$(get_meta '.gpu.kfd_major')
KFD_MINOR=$(get_meta '.gpu.kfd_minor')
RENDER_NODE=$(get_meta '.gpu.render_node')
RENDER_MAJOR=$(get_meta '.gpu.render_major')
RENDER_MINOR=$(get_meta '.gpu.render_minor')
MODELS_SRC=$(get_meta '.models_bind_src')
MODELS_DST=$(get_meta '.models_bind_dst')

# --- Check VMID free ---
if pct status "$VMID" &>/dev/null; then
  echo -e "${RD}[ERROR]${CL} LXC $VMID already exists. Remove it first."; exit 1
fi

# --- Download Debian template if needed ---
TEMPLATE="debian-12-standard_12.12-1_amd64.tar.zst"
TEMPLATE_PATH="/var/lib/vz/template/cache/$TEMPLATE"
if [ ! -f "$TEMPLATE_PATH" ]; then
  echo "Downloading Debian 12 LXC template..."
  pveam update >/dev/null
  pveam download local "$TEMPLATE" >/dev/null
fi

# --- Create LXC ---
echo -e "${BOLD}Creating LXC $VMNAME (ID: $VMID)...${CL}"
pct create "$VMID" "local:vztmpl/$TEMPLATE" \
  --hostname "$VMNAME" \
  --cores "$CORES" \
  --memory "$MEMORY" \
  --swap 0 \
  --rootfs "${STORAGE}:${DISK//G/}" \
  --net0 "name=eth0,bridge=${BRIDGE},ip=dhcp" \
  --ostype debian \
  --unprivileged 0 \
  --features "nesting=1" \
  --tags "$VMTAG" \
  --onboot 1 \
  >/dev/null

# --- GPU passthrough: cgroup2 device access ---
echo "Configuring GPU passthrough..."
cat >> "/etc/pve/lxc/${VMID}.conf" <<EOF

# GPU passthrough — generated by Create-TAPPaaS-LXC.sh
lxc.cgroup2.devices.allow: c ${KFD_MAJOR}:${KFD_MINOR} rwm
lxc.cgroup2.devices.allow: c ${RENDER_MAJOR}:${RENDER_MINOR} rwm
lxc.mount.entry: /dev/kfd dev/kfd none bind,optional,create=file
lxc.mount.entry: /dev/dri/${RENDER_NODE} dev/dri/${RENDER_NODE} none bind,optional,create=file
EOF

# --- Models bind-mount ---
echo "Configuring models bind-mount: $MODELS_SRC → $MODELS_DST"
mkdir -p "$MODELS_SRC"
cat >> "/etc/pve/lxc/${VMID}.conf" <<EOF
mp0: ${MODELS_SRC},mp=${MODELS_DST}
EOF

# --- Start LXC + install Docker + ROCm ---
echo "Starting LXC..."
pct start "$VMID"
sleep 5

echo "Installing Docker + ROCm inside LXC..."
pct exec "$VMID" -- bash -c "
  apt-get update -qq && apt-get install -y -qq curl gnupg2 ca-certificates lsb-release
  curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker.gpg
  echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable' \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq && apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable --now docker
"

echo -e "\n${GN}✅ LXC $VMNAME (ID: $VMID) created and ready.${CL}"
echo "Next: run 'docker compose up -d' inside the LXC, or use update.sh."