"""Render a per-node Proxmox VE ``answer.toml`` (design N3/N4).

Field set per the PVE >= 8.2 automated-installation docs
(https://pve.proxmox.com/wiki/Automated_Installation): ``[global]`` with
keyboard/country/fqdn/mailto/timezone/root-password/root-ssh-keys,
``[network]`` from-dhcp, ``[disk-setup]`` with filesystem + zfs.raid +
disk-list.

TODO(V-2): validate the exact schema against the deployed PVE version's
``proxmox-auto-install-assistant validate-answer`` on a PVE node — key
casing (kebab-case per docs) and the accepted zfs.raid values must be
confirmed on hardware before first use.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from .log import warn

DEFAULT_KEYBOARD = "en-us"
DEFAULT_COUNTRY = "us"
DEFAULT_TIMEZONE = "UTC"

# cluster --pool topology -> PVE installer zfs.raid value.
# Declared pools install as ZFS; 'single' is a one-disk raid0 (design N3:
# "filesystem zfs raid0 for declared pools").
LAYOUT_TO_ZFS_RAID = {
    "single": "raid0",
    "stripe": "raid0",
    "mirror": "raid1",
    "raidz": "raidz-1",
    "raidz2": "raidz-2",
}


def _toml_str(value: str) -> str:
    """Encode a python string as a TOML basic string.

    JSON string escaping is a valid subset of TOML basic-string escaping.
    """
    return json.dumps(str(value))


def _toml_str_list(values) -> str:
    return "[" + ", ".join(_toml_str(v) for v in values) + "]"


def load_site(site_path) -> dict:
    """Best-effort read of site.json ({} when missing/unreadable)."""
    try:
        return json.loads(Path(site_path).read_text())
    except (OSError, json.JSONDecodeError) as e:
        warn(f"cannot read site.json at {site_path}: {e} — using defaults")
        return {}


def render_answer(
    name: str,
    domain: str,
    root_password: str,
    ssh_keys,
    pools,
    country: str = DEFAULT_COUNTRY,
    tz: str = DEFAULT_TIMEZONE,
    mailto: str = "",
    keyboard: str = DEFAULT_KEYBOARD,
) -> str:
    """Render answer.toml for a registered node.

    Args:
        name: Node name (hostname part).
        domain: DNS domain for the FQDN (mgmt plane, e.g. mgmt.internal).
        root_password: Generated plaintext root password (stored 0600 by
            the caller; day-2 access is SSH-keys-only per design §4).
        ssh_keys: Public keys placed in root's authorized_keys by the
            installer.
        pools: Registration pool dicts ({name, layout, disks}); the FIRST
            pool is the installer's root pool (ZFS). Empty => ext4
            TODO-marker fallback.
        country / tz / mailto / keyboard: site-level installer settings.
    """
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    fqdn = f"{name}.{domain}"
    mailto = mailto or f"root@{domain}"

    lines = [
        f"# answer.toml for {fqdn} — generated by TAPPaaS node-provisioner {now}",
        "# One-shot: the matching registration is consumed after this answer.",
        "# TODO(V-2): schema validated against PVE docs only — run",
        "#   proxmox-auto-install-assistant validate-answer <this file>",
        "# on a PVE node to confirm for the deployed version.",
        "",
        "[global]",
        f"keyboard = {_toml_str(keyboard)}",
        f"country = {_toml_str(country.lower())}",
        f"fqdn = {_toml_str(fqdn)}",
        f"mailto = {_toml_str(mailto)}",
        f"timezone = {_toml_str(tz)}",
        f"root-password = {_toml_str(root_password)}",
        f"root-ssh-keys = {_toml_str_list(ssh_keys)}",
        "",
        "[network]",
        'source = "from-dhcp"',
        "",
        "[disk-setup]",
    ]

    if pools:
        pool = pools[0]
        raid = LAYOUT_TO_ZFS_RAID.get(pool.get("layout", "single"))
        if raid is None:
            warn(f"unknown pool layout {pool.get('layout')!r} — using raid0")
            raid = "raid0"
        lines += [
            'filesystem = "zfs"',
            f'zfs.raid = {_toml_str(raid)}',
            f"disk-list = {_toml_str_list(pool.get('disks', []))}",
        ]
        if len(pools) > 1:
            extra = ", ".join(p.get("name", "?") for p in pools[1:])
            lines += [
                f"# NOTE: additional declared pools ({extra}) are NOT created "
                "by the installer;",
                "# they are created post-join by the storage plane "
                "(config-storage.sh / site.json).",
            ]
    else:
        lines += [
            "# TODO(V-2): no storage pool declared for this node — falling "
            "back to ext4",
            "# on the first disk. Register with --pool "
            "'tanka1=single:<disk>' for the",
            "# intended ZFS layout (the platform layer expects tanka1).",
            'filesystem = "ext4"',
            'disk-list = ["sda"]',
        ]

    return "\n".join(lines) + "\n"


def answer_settings_from_site(site: dict) -> dict:
    """Extract installer settings (country/timezone/mailto) from site.json."""
    location = site.get("location") or {}
    return {
        "country": (location.get("country") or DEFAULT_COUNTRY),
        "tz": (location.get("timezone") or DEFAULT_TIMEZONE),
        "mailto": (site.get("email") or ""),
    }
