#!/usr/bin/env bash
# lib/provision.sh — nixos-anywhere provisioning helpers for the ADR-010 satellite.
# Encodes the flow validated live 2026-07-01 (Debian -> NixOS 25.05, declarative
# wg-infra tunnel). shellcheck shell=bash

SATELLITE_SRC="${SATELLITE_SRC:-$HOME/TAPPaaS/src/foundation/satellite}"
SATELLITE_DEBIAN_SRC="${SATELLITE_DEBIAN_SRC:-${SATELLITE_SRC}/debian}"
PROVISION_KEY="${PROVISION_KEY:-$HOME/.ssh/sat-provision}"

# --- DERIVED DEFAULTS (single source of truth) --------------------------------
# NOT exposed in satellite.json (ADR-010 "sensible defaults"). Operators only pick
# roles/provider/host/S3; everything below is defaulted here. Env-overridable for
# advanced/multi-satellite use (e.g. a second satellite needs its own /31).
: "${SAT_SAT_ADDR:=10.255.0.0}"   # /31 satellite end
: "${SAT_HOME_ADDR:=10.255.0.1}"  # /31 home (OPNsense) end
: "${SAT_WGPORT:=51820}"          # infra tunnel UDP listener
: "${SAT_ADMIN_WGPORT:=51821}"    # admin-vpn relay + OPNsense admin-WG listen
: "${SAT_KEEPALIVE:=25}"          # PersistentKeepalive (home side; keeps CGNAT pinhole open)
: "${SAT_BOOT_DEVICE:=/dev/sda}"  # Hetzner x86 single disk
: "${SAT_REBOOT_TIME:=03:30}"     # Debian (Option 3) unattended-upgrades auto-reboot window
: "${SAT_PROXY_PROTOCOL:=false}"  # reverse-proxy: PROXY-protocol v2 (gate on until Caddy expects it)
# backup role (P6) — the satellite PULLS from home. Datastore + retention defaults.
: "${SAT_DATASTORE_NAME:=tappaas-offsite}"          # local PBS datastore (pull destination)
: "${SAT_DATASTORE_PATH:=/srv/pbs/tappaas-offsite}" # on a ZFS dataset for a real vault
: "${SAT_REMOTE_NAME:=home}"                        # PBS 'remote' pointing at home PBS
: "${SAT_HOME_PBS_PORT:=8007}"
: "${SAT_SYNC_SCHEDULE:=daily}"
: "${SAT_REMOVE_VANISHED:=false}"                   # home deleting a snapshot must NOT delete our copy
: "${SAT_PRUNE_SCHEDULE:=daily}"
: "${SAT_PRUNE_KEEP:=--keep-daily 7 --keep-weekly 4 --keep-monthly 6}"

# Generate satellite-settings.nix from the operator-facing satellite.json + the
# home OPNsense pubkey + the derived defaults. Args: <config-json> <home-pubkey> <out-file>
sat_gen_settings() {
    local cfg="$1" home_pub="$2" out="$3"
    local name roles_nix keys_nix
    name="$(jq -r '.name // "satellite"' "${cfg}")"
    roles_nix="$(jq -r '(.roles // []) | map("\"" + . + "\"") | join(" ")' "${cfg}")"
    keys_nix="$(jq -r '(.host.operatorSshKeys // []) | map("    \"" + . + "\"") | join("\n")' "${cfg}")"
    [[ "$(jq -r '(.host.operatorSshKeys // []) | length' "${cfg}")" -gt 0 ]] \
        || { echo "ERROR: ${cfg} has no host.operatorSshKeys (operator out-of-band key required)" >&2; return 1; }
    cat > "${out}" <<EOF
# GENERATED by satellite-manager from ${cfg##*/} — do not edit by hand.
# Operator-facing values come from satellite.json; the rest are satellite-manager
# defaults (ADR-010 "sensible defaults" — lib/provision.sh).
{
  hostName = "${name}";
  bootDevice = "${SAT_BOOT_DEVICE}";
  roles = [ ${roles_nix} ];
  tunnel = {
    satelliteAddr = "${SAT_SAT_ADDR}";
    homeAddr = "${SAT_HOME_ADDR}";
    wgPort = ${SAT_WGPORT};
  };
  homePublicKey = "${home_pub}";
  homeCaddyAddr = "${SAT_HOME_ADDR}";
  adminWgPort = ${SAT_ADMIN_WGPORT};
  adminListenPort = ${SAT_ADMIN_WGPORT};
  homeAdminWgAddr = "${SAT_HOME_ADDR}";
  proxyProtocol = false;
  operatorSshKeys = [
${keys_nix}
  ];
}
EOF
}

# Write the operator-facing satellite config JSON (the MANAGER owns the JSON —
# operators pass flags, not hand-edited files). Args:
#   <out> <name> <provider> <publicIp> <sshKey> <roles-csv> [bucket] [s3-endpoint]
sat_write_config() {
    local out="$1" name="$2" provider="$3" ip="$4" key="$5" roles="$6" bucket="${7:-}" s3ep="${8:-https://hel1.your-objectstorage.com}" os="${9:-debian}"
    local roles_json backup_json='null'
    roles_json="$(printf '%s' "${roles}" | jq -R 'split(",") | map(select(length>0))')"
    [[ -n "${bucket}" ]] && backup_json="$(jq -n --arg ep "${s3ep}" --arg b "${bucket}" '{s3:{endpoint:$ep,bucket:$b}}')"
    jq -n \
        --arg name "${name}" --arg provider "${provider}" --arg ip "${ip}" --arg key "${key}" --arg os "${os}" \
        --argjson roles "${roles_json}" --argjson backup "${backup_json}" \
        '{
           kind:"external-host", tier:"foundation", name:$name, os:$os, roles:$roles, dependsOn:[],
           provider:{type:$provider, allocation:"portal"},
           host:{publicIp:$ip, sshUser:"root", operatorSshKeys:[$key]}
         } + (if $backup != null then {backup:$backup} else {} end)' > "${out}"
}

# Assemble a standalone deploy dir (flake + disko + satellite.nix + settings).
# Args: <settings-file> ; echoes the deploy dir.
sat_assemble_deploy() {
    local settings="$1" d
    d="$(mktemp -d /tmp/sat-deploy.XXXXXX)"
    cp "${SATELLITE_SRC}/flake.nix" "${SATELLITE_SRC}/disk-config.nix" "${SATELLITE_SRC}/satellite.nix" "${d}/"
    cp "${settings}" "${d}/satellite-settings.nix"
    echo "${d}"
}

# Run nixos-anywhere. Args: <deploy-dir> <root@ip>
sat_nixos_anywhere() {
    local d="$1" target="$2"
    ( cd "${d}" && nix run github:nix-community/nixos-anywhere \
        --extra-experimental-features 'nix-command flakes' -- \
        --flake '.#satellite' --target-host "${target}" \
        -i "${PROVISION_KEY}" \
        --ssh-option StrictHostKeyChecking=accept-new --ssh-option UserKnownHostsFile=/dev/null )
}

# Read back the satellite's wg-infra PUBLIC key over SSH, with retries for the
# post-install reboot. Post-reformat the satellite trusts ONLY the OPERATOR key
# (the provisioning key is gone — §7.3), and cicd must NOT hold the operator key.
# So this uses the ambient SSH agent (run `satellite-manager install` over an
# agent-forwarded session, `ssh -A`, so your operator key is reachable). An
# explicit key file can be passed as $2 when available. Args: <root@ip> [key]
sat_read_pubkey() {
    local target="$1" key="${2:-}" pub ident=()
    [[ -n "${key}" ]] && ident=(-i "${key}" -o IdentitiesOnly=yes)
    for _ in $(seq 1 30); do
        pub="$(ssh "${ident[@]}" -o StrictHostKeyChecking=accept-new \
                 -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -o ConnectTimeout=10 \
                 "${target}" 'wg show wg-infra public-key' 2>/dev/null)" || true
        [[ -n "${pub}" ]] && { echo "${pub}"; return 0; }
        sleep 10
    done
    return 1
}

# ═══════════════════════════════════════════════════════════════════════════
# DEBIAN SATELLITE (ADR-010 Option 3) — an alternative to the NixOS path above.
# Same SAT_* derived values, same OPNsense home side; renders plain Debian config
# files instead of satellite-settings.nix, and provisions an already-booted
# Debian host over SSH (no nixos-anywhere). See satellite/debian/README.md.
# ═══════════════════════════════════════════════════════════════════════════

# Render the per-role Debian config files from the operator JSON + derived
# SAT_* defaults + the home OPNsense pubkey, into <out-dir>. Only the files a
# role needs are written (provision-debian.sh is role-gated to match).
# Args: <config-json> <home-pubkey> <out-dir>
sat_gen_debian_configs() {
    local cfg="$1" home_pub="$2" out="$3"
    local roles pp=""
    roles="$(jq -r '(.roles // []) | join(" ")' "${cfg}")"
    [[ "$(jq -r '(.host.operatorSshKeys // []) | length' "${cfg}")" -gt 0 ]] \
        || { echo "ERROR: ${cfg} has no host.operatorSshKeys (operator out-of-band key required)" >&2; return 1; }
    _sat_has_role() { [[ " ${roles} " == *" $1 "* ]]; }
    mkdir -p "${out}"

    printf 'ROLES="%s"\n' "${roles}" > "${out}/roles.env"

    jq -r '(.host.operatorSshKeys // [])[]' "${cfg}" > "${out}/operator_authorized_keys"

    # WireGuard infra tunnel (always). Private key stays in a 0600 keyfile on-host
    # (injected via PostUp) — never in this rendered config. Home dials in, so no
    # Endpoint here; the [Peer] is added once the OPNsense pubkey is known.
    {
        echo "# GENERATED by satellite-manager — WireGuard infra tunnel (ADR-010)."
        echo "# No private key here: injected via PostUp from /etc/wireguard/wg-infra.key (0600)."
        echo "[Interface]"
        echo "Address = ${SAT_SAT_ADDR}/31"
        echo "ListenPort = ${SAT_WGPORT}"
        echo "PostUp = wg set %i private-key /etc/wireguard/wg-infra.key"
        if [[ -n "${home_pub}" ]]; then
            # AllowedIPs = what the satellite routes INTO the tunnel. Base: the OPNsense
            # /31 end. The backup role adds the home PBS host so the satellite can PULL
            # from it over the tunnel (edge -> home PBS:8007 is allowed on OPNsense).
            local allowed="${SAT_HOME_ADDR}/32" pbs_host
            if _sat_has_role backup; then
                pbs_host="$(jq -r '.backup.pull.homePbsHost // empty' "${cfg}")"
                [[ -n "${pbs_host}" ]] && allowed="${allowed}, ${pbs_host}/32"
            fi
            echo ""
            echo "[Peer]"
            echo "PublicKey = ${home_pub}"
            echo "AllowedIPs = ${allowed}"
        fi
    } > "${out}/wg-infra.conf"

    # Host firewall (+ admin-vpn NAT relay) — nftables. Role-gated allows.
    {
        echo "#!/usr/sbin/nft -f"
        echo "# GENERATED by satellite-manager — host firewall$(_sat_has_role admin-vpn && echo ' + admin-vpn NAT relay')."
        echo "flush ruleset"
        echo ""
        echo "table inet filter {"
        echo "  chain input {"
        echo "    type filter hook input priority filter; policy drop;"
        echo "    ct state established,related accept"
        echo "    ct state invalid drop"
        echo "    iif lo accept"
        echo "    ip protocol icmp accept"
        echo "    ip6 nexthdr ipv6-icmp accept"
        echo "    tcp dport 22 accept        # operator SSH (out-of-band)"
        echo "    udp dport ${SAT_WGPORT} accept       # infra tunnel"
        _sat_has_role reverse-proxy && echo "    tcp dport { 80, 443 } accept  # reverse-proxy passthrough"
        _sat_has_role admin-vpn     && echo "    udp dport ${SAT_ADMIN_WGPORT} accept       # admin-vpn relay"
        echo "  }"
        echo "  chain forward {"
        echo "    type filter hook forward priority filter; policy drop;"
        echo "    ct state established,related accept"
        _sat_has_role admin-vpn && echo "    ip daddr ${SAT_HOME_ADDR} udp dport ${SAT_ADMIN_WGPORT} accept  # admin-vpn: relay -> OPNsense over tunnel"
        echo "  }"
        echo "  chain output { type filter hook output priority filter; policy accept; }"
        echo "}"
        if _sat_has_role admin-vpn; then
            echo ""
            echo "# admin-vpn BLIND UDP relay — DNAT :${SAT_ADMIN_WGPORT} to the OPNsense admin-WG"
            echo "# listener over the infra tunnel; the satellite holds no admin keys (ADR-010 §6)."
            echo "table ip adminvpn {"
            echo "  chain prerouting {"
            echo "    type nat hook prerouting priority dstnat; policy accept;"
            echo "    udp dport ${SAT_ADMIN_WGPORT} dnat to ${SAT_HOME_ADDR}:${SAT_ADMIN_WGPORT}"
            echo "  }"
            echo "  chain postrouting {"
            echo "    type nat hook postrouting priority srcnat; policy accept;"
            echo "    ip daddr ${SAT_HOME_ADDR} udp dport ${SAT_ADMIN_WGPORT} masquerade"
            echo "  }"
            echo "}"
        fi
    } > "${out}/nftables.conf"

    # reverse-proxy — nginx L4 stream passthrough (ADR-010 §2/§5.8).
    if _sat_has_role reverse-proxy; then
        [[ "${SAT_PROXY_PROTOCOL}" == "true" ]] && pp=$'\n      proxy_protocol on;'
        cat > "${out}/nginx-stream.conf" <<EOF
# GENERATED by satellite-manager — nginx L4 stream passthrough (ADR-010 §2).
# The satellite NEVER terminates TLS: all :443 -> Caddy-on-OPNsense over the tunnel;
# :80 too (Caddy issues the redirect). Single-purpose config (stream only).
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;
events { worker_connections 1024; }
stream {
    server {
      listen 443;
      proxy_pass ${SAT_HOME_ADDR}:443;${pp}
    }
    server {
      listen 80;
      proxy_pass ${SAT_HOME_ADDR}:80;${pp}
    }
}
EOF
    fi

    # admin-vpn — enable IP forwarding for the relay.
    if _sat_has_role admin-vpn; then
        printf 'net.ipv4.ip_forward = 1\n' > "${out}/99-tappaas-ipforward.conf"
    fi

    # self-patching — unattended-upgrades (always). Security origin + reboot window.
    cat > "${out}/20auto-upgrades" <<'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF
    cat > "${out}/52tappaas-unattended-upgrades" <<EOF
// GENERATED by satellite-manager — TAPPaaS unattended-upgrades policy (ADR-010).
// Security-origin auto-patching + a scheduled auto-reboot window. For a vault this
// is deliberately conservative (security updates only, not a full dist-upgrade).
Unattended-Upgrade::Origins-Pattern {
    "origin=Debian,codename=\${distro_codename},label=Debian-Security";
    "origin=Debian,codename=\${distro_codename}-security,label=Debian-Security";
};
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "true";
Unattended-Upgrade::Automatic-Reboot-Time "${SAT_REBOOT_TIME}";
EOF
}

# Assemble a Debian deploy dir: the rendered configs + the on-host installer.
# Args: <configs-dir> ; echoes the deploy dir (== configs-dir, with the script added).
sat_assemble_debian_deploy() {
    local cfgdir="$1"
    cp "${SATELLITE_DEBIAN_SRC}/provision-debian.sh" "${cfgdir}/provision-debian.sh"
    chmod +x "${cfgdir}/provision-debian.sh"
    echo "${cfgdir}"
}

# Provision an already-booted Debian host: ship the deploy dir and run the
# installer over SSH. No nixos-anywhere, no reformat. Uses the operator's key via
# the ambient agent (run install over `ssh -A`); an explicit key may be passed.
# Args: <deploy-dir> <root@ip> [key]
sat_provision_debian() {
    local d="$1" target="$2" key="${3:-}" ident=()
    [[ -n "${key}" ]] && ident=(-i "${key}" -o IdentitiesOnly=yes)
    local sshopt=(-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR)
    ssh "${ident[@]}" "${sshopt[@]}" "${target}" 'rm -rf /root/tappaas-satellite && mkdir -p /root/tappaas-satellite' \
        || { echo "ERROR: cannot reach ${target} over SSH" >&2; return 1; }
    scp "${ident[@]}" "${sshopt[@]}" -r "${d}/." "${target}:/root/tappaas-satellite/" >/dev/null \
        || { echo "ERROR: scp of the deploy dir to ${target} failed" >&2; return 1; }
    ssh "${ident[@]}" "${sshopt[@]}" "${target}" \
        'cd /root/tappaas-satellite && bash ./provision-debian.sh'
}

# Render the backup-role config (backup.env) from the satellite JSON + SAT_*
# defaults, into <out-dir>. If a home-PBS read-only token is available (env
# TAPPAAS_SAT_PBS_TOKEN, or a file at $TAPPAAS_SAT_PBS_TOKEN_FILE), write it as the
# 0600 pbs-remote-token so provision-backup.sh can wire the pull; otherwise leave
# it out (provision-backup.sh sets up PBS+datastore and prints the token runbook).
# Args: <config-json> <out-dir>
sat_gen_backup_config() {
    local cfg="$1" out="$2"
    mkdir -p "${out}"
    local ds_name ds_path pbs_host pbs_store authid fp sched homen
    ds_name="$(jq -r --arg d "${SAT_DATASTORE_NAME}" '.backup.datastore.name // $d' "${cfg}")"
    ds_path="$(jq -r --arg d "${SAT_DATASTORE_PATH}" '.backup.datastore.path // $d' "${cfg}")"
    pbs_host="$(jq -r '.backup.pull.homePbsHost // empty' "${cfg}")"
    pbs_store="$(jq -r '.backup.pull.homeDatastore // "tappaas"' "${cfg}")"
    authid="$(jq -r '.backup.pull.authId // "satellite@pbs!pull"' "${cfg}")"
    fp="$(jq -r '.backup.pull.fingerprint // empty' "${cfg}")"
    sched="$(jq -r --arg d "${SAT_SYNC_SCHEDULE}" '.backup.pull.schedule // $d' "${cfg}")"
    homen="$(jq -r '.backup.pull.homeNs // empty' "${cfg}")"
    cat > "${out}/backup.env" <<EOF
# GENERATED by satellite-manager — satellite backup role (ADR-010 P6, pull model).
DATASTORE_NAME="${ds_name}"
DATASTORE_PATH="${ds_path}"
HOME_PBS_HOST="${pbs_host}"
HOME_PBS_PORT="${SAT_HOME_PBS_PORT}"
HOME_PBS_DATASTORE="${pbs_store}"
HOME_PBS_NS="${homen}"
REMOTE_NAME="${SAT_REMOTE_NAME}"
REMOTE_AUTHID="${authid}"
REMOTE_FINGERPRINT="${fp}"
SYNC_JOB_ID="offsite-${SAT_REMOTE_NAME}"
SYNC_NS="remote/${SAT_REMOTE_NAME}"
SYNC_SCHEDULE="${sched}"
REMOVE_VANISHED="${SAT_REMOVE_VANISHED}"
PRUNE_SCHEDULE="${SAT_PRUNE_SCHEDULE}"
PRUNE_KEEP="${SAT_PRUNE_KEEP}"
EOF
    # Home read-only token SECRET (never committed; out-of-band). Optional.
    local tok=""
    [[ -n "${TAPPAAS_SAT_PBS_TOKEN:-}" ]] && tok="${TAPPAAS_SAT_PBS_TOKEN}"
    [[ -z "${tok}" && -n "${TAPPAAS_SAT_PBS_TOKEN_FILE:-}" && -s "${TAPPAAS_SAT_PBS_TOKEN_FILE}" ]] \
        && tok="$(< "${TAPPAAS_SAT_PBS_TOKEN_FILE}")"
    if [[ -n "${tok}" ]]; then
        ( umask 077; printf '%s' "${tok}" > "${out}/pbs-remote-token" )
    fi
}

# Ship provision-backup.sh into an already-assembled deploy dir. Args: <deploy-dir>
sat_assemble_backup_deploy() {
    cp "${SATELLITE_DEBIAN_SRC}/provision-backup.sh" "$1/provision-backup.sh"
    chmod +x "$1/provision-backup.sh"
}

# Run the backup-role installer on the satellite. Args: <deploy-dir> <root@ip> [key]
sat_provision_backup() {
    local d="$1" target="$2" key="${3:-}" ident=()
    [[ -n "${key}" ]] && ident=(-i "${key}" -o IdentitiesOnly=yes)
    local sshopt=(-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR)
    scp "${ident[@]}" "${sshopt[@]}" -r "${d}/." "${target}:/root/tappaas-satellite/" >/dev/null \
        || { echo "ERROR: scp backup deploy to ${target} failed" >&2; return 1; }
    ssh "${ident[@]}" "${sshopt[@]}" "${target}" \
        'cd /root/tappaas-satellite && bash ./provision-backup.sh'
}

# Ensure ONE least-privilege edge(/31) -> <dest>:<port> pass rule on the OPNsense
# WireGuard interface (idempotent by description). The satellite is a semi-trusted
# relay: it gets ROLE-GATED reach to exactly these endpoints and NOTHING else
# (ADR-010 §4.3). Does NOT apply — batch, then call the apply once. Validated live
# 2026-07-03: without these the satellite's tunnelled traffic is dropped by OPNsense.
# Args: <description> <TCP|UDP> <dest-net> <dest-port>
sat_ensure_edge_rule() {
    local desc="$1" proto="$2" dest="$3" port="$4"
    command -v _ow_api >/dev/null 2>&1 || { echo "opnsense-wg lib not loaded" >&2; return 1; }
    local exist
    exist="$(_ow_api /api/firewall/filter/searchRule | jq -r --arg d "${desc}" '.rows[]? | select(.description==$d) | .uuid' | head -1)"
    [[ -n "${exist}" ]] && { echo "exists"; return 0; }
    _ow_api -X POST -H 'Content-Type: application/json' \
        -d "{\"rule\":{\"enabled\":\"1\",\"action\":\"pass\",\"interface\":\"wireguard\",\"direction\":\"in\",\"ipprotocol\":\"inet\",\"protocol\":\"${proto}\",\"source_net\":\"${SAT_SAT_ADDR}/31\",\"destination_net\":\"${dest}\",\"destination_port\":\"${port}\",\"description\":\"${desc}\"}}" \
        /api/firewall/filter/addRule | jq -r '.result // empty'
}

# Ensure the role-gated edge firewall rules for the active roles, then apply once.
# reverse-proxy: edge -> Caddy :80/:443. admin-vpn: edge -> OPNsense admin-WG (udp).
# (backup's edge -> home-PBS:8007 is handled by sat_ensure_edge_pbs_rule, which
# needs the operator-supplied home PBS host.) Args: <roles-csv>
sat_ensure_edge_rules() {
    local roles="$1"
    if [[ ",${roles}," == *,reverse-proxy,* ]]; then
        sat_ensure_edge_rule "tappaas-satellite edge->caddy 80"  TCP "${SAT_HOME_ADDR}" 80  >/dev/null
        sat_ensure_edge_rule "tappaas-satellite edge->caddy 443" TCP "${SAT_HOME_ADDR}" 443 >/dev/null
    fi
    if [[ ",${roles}," == *,admin-vpn,* ]]; then
        sat_ensure_edge_rule "tappaas-satellite edge->admin-wg" UDP "${SAT_HOME_ADDR}" "${SAT_ADMIN_WGPORT}" >/dev/null
    fi
    _ow_api -X POST /api/firewall/filter/apply >/dev/null
}

# OPNsense least-privilege rule for the backup role: edge (/31) -> home PBS:8007,
# so the satellite can PULL over the tunnel — and NOTHING else in the cluster
# becomes reachable (ADR-010 §3.3). Idempotent. Args: <home-pbs-host>
sat_ensure_edge_pbs_rule() {
    local pbs_host="$1"
    [[ -n "${pbs_host}" ]] || { echo "no home PBS host — skipped" >&2; return 0; }
    local r; r="$(sat_ensure_edge_rule "tappaas-satellite edge->home-pbs" TCP "${pbs_host}" "${SAT_HOME_PBS_PORT}")"
    [[ "${r}" == "exists" ]] || _ow_api -X POST /api/firewall/filter/apply >/dev/null
    echo "${r}"
}
