#!/usr/bin/env bash
# lib/provision.sh — nixos-anywhere provisioning helpers for the ADR-010 satellite.
# Encodes the flow validated live 2026-07-01 (Debian -> NixOS 25.05, declarative
# wg-infra tunnel). shellcheck shell=bash

SATELLITE_SRC="${SATELLITE_SRC:-$HOME/TAPPaaS/src/foundation/satellite}"
PROVISION_KEY="${PROVISION_KEY:-$HOME/.ssh/sat-provision}"

# Generate satellite-settings.nix from satellite.json + the home OPNsense pubkey.
# Args: <config-json> <home-pubkey> <out-file>
sat_gen_settings() {
    local cfg="$1" home_pub="$2" out="$3"
    local name roles_nix keys_nix sat_addr home_addr wgport
    name="$(jq -r '.name // "satellite"' "${cfg}")"
    wgport="$(jq -r '.tunnel.wgPort // 51820' "${cfg}")"
    sat_addr="$(jq -r '.tunnel.satelliteAddr // "10.255.0.0"' "${cfg}")"
    home_addr="$(jq -r '.tunnel.homeAddr // "10.255.0.1"' "${cfg}")"
    # roles + operator keys as nix lists
    roles_nix="$(jq -r '(.roles // []) | map("\"" + . + "\"") | join(" ")' "${cfg}")"
    keys_nix="$(jq -r '(.host.operatorSshKeys // []) | map("    \"" + . + "\"") | join("\n")' "${cfg}")"
    [[ -n "$(jq -r '.host.operatorSshKeys // [] | length' "${cfg}")" && "$(jq -r '.host.operatorSshKeys // [] | length' "${cfg}")" -gt 0 ]] \
        || { echo "ERROR: ${cfg} has no host.operatorSshKeys (operator out-of-band key required)" >&2; return 1; }
    cat > "${out}" <<EOF
# GENERATED by satellite-manager from ${cfg##*/} — do not edit by hand.
{
  hostName = "${name}";
  bootDevice = "$(jq -r '.provider.bootDevice // "/dev/sda"' "${cfg}")";
  roles = [ ${roles_nix} ];
  tunnel = {
    satelliteAddr = "${sat_addr}";
    homeAddr = "${home_addr}";
    wgPort = ${wgport};
  };
  homePublicKey = "${home_pub}";
  homeCaddyAddr = "${home_addr}";
  adminWgPort = $(jq -r '.adminVpn.adminWgPort // 51821' "${cfg}");
  homeAdminWgAddr = "${home_addr}";
  operatorSshKeys = [
${keys_nix}
  ];
}
EOF
}

# Assemble a standalone deploy dir (flake + disko + satellite.nix + settings).
# Args: <settings-file> ; echoes the deploy dir.
sat_assemble_deploy() {
    local settings="$1" d
    d="$(mktemp -d /tmp/sat-deploy.XXXXXX)"
    cp "${SATELLITE_SRC}/flake.nix" "${SATELLITE_SRC}/disk-config.nix" "${SATELLITE_SRC}/satellite.nix" "${d}/"
    cp "${settings}" "${d}/satellite-settings.nix"
    echo "${d}"
}

# Run nixos-anywhere. Args: <deploy-dir> <root@ip>
sat_nixos_anywhere() {
    local d="$1" target="$2"
    ( cd "${d}" && nix run github:nix-community/nixos-anywhere \
        --extra-experimental-features 'nix-command flakes' -- \
        --flake '.#satellite' --target-host "${target}" \
        -i "${PROVISION_KEY}" \
        --ssh-option StrictHostKeyChecking=accept-new --ssh-option UserKnownHostsFile=/dev/null )
}

# Read back the satellite's wg-infra PUBLIC key over SSH, with retries for the
# post-install reboot. Post-reformat the satellite trusts ONLY the OPERATOR key
# (the provisioning key is gone — §7.3), and cicd must NOT hold the operator key.
# So this uses the ambient SSH agent (run `satellite-manager install` over an
# agent-forwarded session, `ssh -A`, so your operator key is reachable). An
# explicit key file can be passed as $2 when available. Args: <root@ip> [key]
sat_read_pubkey() {
    local target="$1" key="${2:-}" pub ident=()
    [[ -n "${key}" ]] && ident=(-i "${key}" -o IdentitiesOnly=yes)
    for _ in $(seq 1 30); do
        pub="$(ssh "${ident[@]}" -o StrictHostKeyChecking=accept-new \
                 -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -o ConnectTimeout=10 \
                 "${target}" 'wg show wg-infra public-key' 2>/dev/null)" || true
        [[ -n "${pub}" ]] && { echo "${pub}"; return 0; }
        sleep 10
    done
    return 1
}
