#!/usr/bin/env bash
# lib/provision.sh — nixos-anywhere provisioning helpers for the ADR-010 satellite.
# Encodes the flow validated live 2026-07-01 (Debian -> NixOS 25.05, declarative
# wg-infra tunnel). shellcheck shell=bash

SATELLITE_SRC="${SATELLITE_SRC:-$HOME/TAPPaaS/src/foundation/satellite}"
PROVISION_KEY="${PROVISION_KEY:-$HOME/.ssh/sat-provision}"

# --- DERIVED DEFAULTS (single source of truth) --------------------------------
# NOT exposed in satellite.json (ADR-010 "sensible defaults"). Operators only pick
# roles/provider/host/S3; everything below is defaulted here. Env-overridable for
# advanced/multi-satellite use (e.g. a second satellite needs its own /31).
: "${SAT_SAT_ADDR:=10.255.0.0}"   # /31 satellite end
: "${SAT_HOME_ADDR:=10.255.0.1}"  # /31 home (OPNsense) end
: "${SAT_WGPORT:=51820}"          # infra tunnel UDP listener
: "${SAT_ADMIN_WGPORT:=51821}"    # admin-vpn relay + OPNsense admin-WG listen
: "${SAT_KEEPALIVE:=25}"          # PersistentKeepalive (home side; keeps CGNAT pinhole open)
: "${SAT_BOOT_DEVICE:=/dev/sda}"  # Hetzner x86 single disk

# Generate satellite-settings.nix from the operator-facing satellite.json + the
# home OPNsense pubkey + the derived defaults. Args: <config-json> <home-pubkey> <out-file>
sat_gen_settings() {
    local cfg="$1" home_pub="$2" out="$3"
    local name roles_nix keys_nix
    name="$(jq -r '.name // "satellite"' "${cfg}")"
    roles_nix="$(jq -r '(.roles // []) | map("\"" + . + "\"") | join(" ")' "${cfg}")"
    keys_nix="$(jq -r '(.host.operatorSshKeys // []) | map("    \"" + . + "\"") | join("\n")' "${cfg}")"
    [[ "$(jq -r '(.host.operatorSshKeys // []) | length' "${cfg}")" -gt 0 ]] \
        || { echo "ERROR: ${cfg} has no host.operatorSshKeys (operator out-of-band key required)" >&2; return 1; }
    cat > "${out}" <<EOF
# GENERATED by satellite-manager from ${cfg##*/} — do not edit by hand.
# Operator-facing values come from satellite.json; the rest are satellite-manager
# defaults (ADR-010 "sensible defaults" — lib/provision.sh).
{
  hostName = "${name}";
  bootDevice = "${SAT_BOOT_DEVICE}";
  roles = [ ${roles_nix} ];
  tunnel = {
    satelliteAddr = "${SAT_SAT_ADDR}";
    homeAddr = "${SAT_HOME_ADDR}";
    wgPort = ${SAT_WGPORT};
  };
  homePublicKey = "${home_pub}";
  homeCaddyAddr = "${SAT_HOME_ADDR}";
  adminWgPort = ${SAT_ADMIN_WGPORT};
  adminListenPort = ${SAT_ADMIN_WGPORT};
  homeAdminWgAddr = "${SAT_HOME_ADDR}";
  proxyProtocol = false;
  operatorSshKeys = [
${keys_nix}
  ];
}
EOF
}

# Write the operator-facing satellite config JSON (the MANAGER owns the JSON —
# operators pass flags, not hand-edited files). Args:
#   <out> <name> <provider> <publicIp> <sshKey> <roles-csv> [bucket] [s3-endpoint]
sat_write_config() {
    local out="$1" name="$2" provider="$3" ip="$4" key="$5" roles="$6" bucket="${7:-}" s3ep="${8:-https://hel1.your-objectstorage.com}"
    local roles_json backup_json='null'
    roles_json="$(printf '%s' "${roles}" | jq -R 'split(",") | map(select(length>0))')"
    [[ -n "${bucket}" ]] && backup_json="$(jq -n --arg ep "${s3ep}" --arg b "${bucket}" '{s3:{endpoint:$ep,bucket:$b}}')"
    jq -n \
        --arg name "${name}" --arg provider "${provider}" --arg ip "${ip}" --arg key "${key}" \
        --argjson roles "${roles_json}" --argjson backup "${backup_json}" \
        '{
           kind:"external-host", tier:"foundation", name:$name, roles:$roles, dependsOn:[],
           provider:{type:$provider, allocation:"portal"},
           host:{publicIp:$ip, sshUser:"root", operatorSshKeys:[$key]}
         } + (if $backup != null then {backup:$backup} else {} end)' > "${out}"
}

# Assemble a standalone deploy dir (flake + disko + satellite.nix + settings).
# Args: <settings-file> ; echoes the deploy dir.
sat_assemble_deploy() {
    local settings="$1" d
    d="$(mktemp -d /tmp/sat-deploy.XXXXXX)"
    cp "${SATELLITE_SRC}/flake.nix" "${SATELLITE_SRC}/disk-config.nix" "${SATELLITE_SRC}/satellite.nix" "${d}/"
    cp "${settings}" "${d}/satellite-settings.nix"
    echo "${d}"
}

# Run nixos-anywhere. Args: <deploy-dir> <root@ip>
sat_nixos_anywhere() {
    local d="$1" target="$2"
    ( cd "${d}" && nix run github:nix-community/nixos-anywhere \
        --extra-experimental-features 'nix-command flakes' -- \
        --flake '.#satellite' --target-host "${target}" \
        -i "${PROVISION_KEY}" \
        --ssh-option StrictHostKeyChecking=accept-new --ssh-option UserKnownHostsFile=/dev/null )
}

# Read back the satellite's wg-infra PUBLIC key over SSH, with retries for the
# post-install reboot. Post-reformat the satellite trusts ONLY the OPERATOR key
# (the provisioning key is gone — §7.3), and cicd must NOT hold the operator key.
# So this uses the ambient SSH agent (run `satellite-manager install` over an
# agent-forwarded session, `ssh -A`, so your operator key is reachable). An
# explicit key file can be passed as $2 when available. Args: <root@ip> [key]
sat_read_pubkey() {
    local target="$1" key="${2:-}" pub ident=()
    [[ -n "${key}" ]] && ident=(-i "${key}" -o IdentitiesOnly=yes)
    for _ in $(seq 1 30); do
        pub="$(ssh "${ident[@]}" -o StrictHostKeyChecking=accept-new \
                 -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -o ConnectTimeout=10 \
                 "${target}" 'wg show wg-infra public-key' 2>/dev/null)" || true
        [[ -n "${pub}" ]] && { echo "${pub}"; return 0; }
        sleep 10
    done
    return 1
}
