#!/usr/bin/env bash
# TAPPaaS Module: nextcloud-hpb — Installation
#
# Nextcloud Talk High-Performance Backend (nextcloud-spreed-signaling + NATS loopback)
#
# Creates the nextcloud-hpb VM on tappaas2 and wires it up to both Nextcloud and coturn
# so no manual steps are needed beyond creating a DNS A record.
#
# Secret planes:
#   Runtime:    /var/lib/nextcloud-hpb/secrets/ on the HPB VM (generated by NixOS hpb-init-secrets on first boot)
#   Management: /home/tappaas/secrets/nextcloud-hpb.env on tappaas-cicd (written here at install time)
#   coturn dep: /home/tappaas/secrets/coturn.env on tappaas-cicd (written by coturn/install.sh)
#
# Usage: ./install.sh <vmname>
# Example: ./install.sh nextcloud-hpb

# Source the shared routines (logging + get_config_value) — NOT the deprecated
# install-vm.sh, which re-runs VM creation and expects /root/tappaas/<vm>.json on the node.
. /home/tappaas/bin/common-install-routines.sh

# run the update script as all update actions are also needed at install time
. ./update.sh

# Effective (variant) module name passed by the engine as $1 — drives all host
# resolution. Read the EFFECTIVE config (e.g. nextcloud-hpb-test.json), never the
# base module json in pwd (which carries the base vmname/zone).
EFFECTIVE="${1:-nextcloud-hpb}"
EFFECTIVE_JSON="/home/tappaas/config/${EFFECTIVE}.json"
VARIANT="$(jq -r '.variant // empty' "${EFFECTIVE_JSON}" 2>/dev/null || true)"

# Own host from the effective (variant) config.
HPB_HOST="$(jq -r '.vmname' "${EFFECTIVE_JSON}").$(jq -r '.zone0' "${EFFECTIVE_JSON}").internal"

# Nextcloud provider — pair with the SAME variant (nextcloud-test ↔ nextcloud-hpb-test);
# fall back to the base config for a production deploy.
NC_JSON="/home/tappaas/config/nextcloud.json"
[[ -n "${VARIANT}" && -f "/home/tappaas/config/nextcloud-${VARIANT}.json" ]] && \
    NC_JSON="/home/tappaas/config/nextcloud-${VARIANT}.json"
NEXTCLOUD_HOST="$(jq -r '.vmname' "${NC_JSON}" 2>/dev/null || echo nextcloud).$(jq -r '.zone0' "${NC_JSON}" 2>/dev/null || echo srv).internal"
PROXY_DOMAIN="$(get_config_value 'proxyDomain')"
HPB_HOST_PART="${PROXY_DOMAIN%%.*}"
HPB_DOMAIN_PART="${PROXY_DOMAIN#*.}"
MGMT_SECRETS="/home/tappaas/secrets/nextcloud-hpb.env"
COTURN_MGMT_SECRETS="/home/tappaas/secrets/coturn.env"
# Runtime secrets directory — must match secretsDir in nextcloud-hpb.nix
HPB_SECRETS_DIR="/var/lib/nextcloud-hpb/secrets"

# Recreate-safe SSH: a redeployed VM (same hostname, new host key) trips strict
# host-key checking. Clear any stale key for the fresh HPB VM, then accept-new
# persists the current key — keeping verification (not blanket-disabled).
SSH_OPTS=(-o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=accept-new)
ssh-keygen -R "${HPB_HOST}" >/dev/null 2>&1 || true

# ── Read HPB_SECRET from runtime plane → save to management plane ────────────
echo ""
info "${BOLD}Reading HPB secrets from VM…${CL}"

HPB_SECRET=$(ssh "${SSH_OPTS[@]}" \
    "tappaas@${HPB_HOST}" \
    "sudo cat ${HPB_SECRETS_DIR}/hpb-secret 2>/dev/null" || true)

if [[ -n "${HPB_SECRET}" ]]; then
    # inline upsert (the toolbox has no upsert_secret)
    mkdir -p "$(dirname "${MGMT_SECRETS}")"
    { grep -v '^HPB_SECRET=' "${MGMT_SECRETS}" 2>/dev/null || true; printf 'HPB_SECRET=%s\n' "${HPB_SECRET}"; } > "${MGMT_SECRETS}.tmp"
    mv "${MGMT_SECRETS}.tmp" "${MGMT_SECRETS}"
    info "  HPB_SECRET saved to management plane (${MGMT_SECRETS})."
else
    die "Could not read HPB_SECRET from ${HPB_SECRETS_DIR}/hpb-secret — NixOS config may not have been deployed (hpb-init-secrets did not run)"
fi

# ── Sync COTURN_SECRET from management plane → HPB VM (runtime) ──────────────
echo ""
info "${BOLD}Syncing coturn TURN secret to HPB VM…${CL}"

COTURN_SECRET=""
if [[ -f "${COTURN_MGMT_SECRETS}" ]]; then
    COTURN_SECRET=$(grep '^COTURN_SECRET=' "${COTURN_MGMT_SECRETS}" | cut -d= -f2- || true)
fi

if [[ -z "${COTURN_SECRET}" ]]; then
    die "COTURN_SECRET not found in ${COTURN_MGMT_SECRETS} — ensure coturn is installed before nextcloud-hpb"
fi

ssh "${SSH_OPTS[@]}" "tappaas@${HPB_HOST}" \
    "printf '%s\n' '${COTURN_SECRET}' \
       | sudo tee ${HPB_SECRETS_DIR}/turn-secret > /dev/null \
     && sudo chown nextcloud-spreed-signaling:nextcloud-spreed-signaling \
          ${HPB_SECRETS_DIR}/turn-secret \
     && sudo chmod 400 ${HPB_SECRETS_DIR}/turn-secret \
     && sudo systemctl restart nextcloud-spreed-signaling.service" \
    || die "Failed to sync TURN secret to HPB VM"
info "  TURN secret synced to runtime plane; nextcloud-spreed-signaling restarted."

# ── Wire the HPB signaling server's backend allow-list + TURN to real hosts ──────
# nextcloud-hpb.nix ships placeholder defaults (nextcloud.srv_work.internal,
# coturn.dmz.internal). The signaling pre-start REGENERATES server.conf from the nix on
# every (re)start, so these must be corrected in the DEPLOYED nix and applied via
# nixos-rebuild — live edits to server.conf do not survive. Talk validates with the
# Nextcloud PUBLIC base URL, so the internal default is rejected with invalid_backend.
echo ""
info "${BOLD}Wiring HPB signaling backend + TURN (nixos-rebuild)…${CL}"
NEXTCLOUD_PROXY="$(jq -r '.config["firewall:proxy"].proxyDomain // .proxyDomain // empty' "${NC_JSON}" 2>/dev/null || true)"
# Nextcloud intentionally doesn't store proxyDomain (it's derived as <vmname>.<domain>;
# see firewall:proxy / identity install-services). Mirror that derivation here so the
# HPB backend allow-list points at Nextcloud's real PUBLIC URL — otherwise it stays at
# the nix placeholder and Talk rejects signaling with invalid_backend.
if [[ -z "${NEXTCLOUD_PROXY}" ]]; then
    _nc_dom="$(get_variant_config "${VARIANT}" 2>/dev/null | jq -r '.domain // empty')"
    _nc_vm="$(jq -r '.vmname // "nextcloud"' "${NC_JSON}" 2>/dev/null || echo nextcloud)"
    [[ -n "${_nc_dom}" ]] && NEXTCLOUD_PROXY="${_nc_vm}.${_nc_dom}"
fi
_coturn_cfg="/home/tappaas/config/coturn.json"
[[ -n "${VARIANT}" && -f "/home/tappaas/config/coturn-${VARIANT}.json" ]] && \
    _coturn_cfg="/home/tappaas/config/coturn-${VARIANT}.json"
_coturn_pub="$(jq -r '.publicDomain // empty' "${_coturn_cfg}" 2>/dev/null || true)"
COTURN_TURN_HOST="${_coturn_pub:-$(jq -r '.vmname' "${_coturn_cfg}").$(jq -r '.zone0' "${_coturn_cfg}").internal}"
if [[ -n "${NEXTCLOUD_PROXY}" ]]; then
    # nixos-rebuild on these VMs needs `-I nixos-config=` (no /etc/nixos/configuration.nix
    # exists — the module nix IS the config, same invocation as update-os.sh).
    ssh "${SSH_OPTS[@]}" "tappaas@${HPB_HOST}" \
        "sudo sed -i -E 's#(urls[[:space:]]*=[[:space:]]*\\[[[:space:]]*)\"[^\"]*\"#\\1\"https://${NEXTCLOUD_PROXY}\"#' /etc/nixos/nextcloud-hpb.nix \
         && sudo sed -i -E 's#turn:[^:\"]*:3478#turn:${COTURN_TURN_HOST}:3478#g' /etc/nixos/nextcloud-hpb.nix \
         && sudo nixos-rebuild switch -I nixos-config=/etc/nixos/nextcloud-hpb.nix" \
        && info "  HPB backend allow-list → https://${NEXTCLOUD_PROXY}; TURN advertise → ${COTURN_TURN_HOST}." \
        || warn "  Failed to wire HPB backend/TURN via nixos-rebuild — check /etc/nixos/nextcloud-hpb.nix on the HPB VM."
else
    warn "  Nextcloud proxyDomain unknown — HPB backend allow-list left at the nix default (invalid_backend risk)."
fi

# ── Configure Nextcloud Talk HPB signaling backend ───────────────────────────
echo ""
info "${BOLD}Configuring Nextcloud Talk signaling backend…${CL}"

# Coturn TURN/STUN endpoint for Nextcloud Talk. External call participants must reach
# it, so prefer coturn's public domain; fall back to the internal host (in-network/test).
COTURN_CFG="/home/tappaas/config/coturn.json"
[[ -n "${VARIANT}" && -f "/home/tappaas/config/coturn-${VARIANT}.json" ]] && \
    COTURN_CFG="/home/tappaas/config/coturn-${VARIANT}.json"
COTURN_PUBLIC="$(jq -r '.publicDomain // empty' "${COTURN_CFG}" 2>/dev/null || true)"
if [[ -n "${COTURN_PUBLIC}" ]]; then
    TURN_SERVER="${COTURN_PUBLIC}:3478"
else
    TURN_SERVER="$(jq -r '.vmname' "${COTURN_CFG}").$(jq -r '.zone0' "${COTURN_CFG}").internal:3478"
fi

# Write HPB_SECRET, HPB_URL, TURN_SECRET and TURN_SERVER — nextcloud-configure-hpb.service
# reads all four from this EnvironmentFile to register the signaling backend (wss://$HPB_URL/
# spreed) plus the TURN/STUN relay. Omitting HPB_URL → unbound var → service fails.
ssh "${SSH_OPTS[@]}" "tappaas@${NEXTCLOUD_HOST}" \
    "printf 'HPB_SECRET=%s\nHPB_URL=%s\nTURN_SECRET=%s\nTURN_SERVER=%s\n' '${HPB_SECRET}' '${PROXY_DOMAIN}' '${COTURN_SECRET}' '${TURN_SERVER}' \
       | sudo tee /etc/secrets/hpb.env > /dev/null \
     && sudo chmod 600 /etc/secrets/hpb.env \
     && sudo chown root:root /etc/secrets/hpb.env" \
    || die "Failed to write /etc/secrets/hpb.env to Nextcloud VM"
info "  /etc/secrets/hpb.env written to Nextcloud VM."

ssh "${SSH_OPTS[@]}" "tappaas@${NEXTCLOUD_HOST}" \
    "sudo systemctl restart nextcloud-configure-hpb.service 2>&1 || true" && \
    info "  nextcloud-configure-hpb.service triggered." || \
    warn "  Failed to trigger nextcloud-configure-hpb.service — reboot Nextcloud VM to apply."

# ── Internal DNS override via OPNsense (split-horizon) ───────────────────────
# Maps ${PROXY_DOMAIN} → 10.2.10.1 (SRV zone gateway) so Nextcloud
# and other internal hosts resolve the public domain to the local Caddy proxy
# instead of the WAN IP (which hairpins back through the ISP router).
echo ""
info "${BOLD}Adding internal DNS override in OPNsense…${CL}"

if dns-manager --no-ssl-verify add "${HPB_HOST_PART}" "${HPB_DOMAIN_PART}" "10.2.10.1" \
        --description "nextcloud-hpb internal split-horizon override"; then
    info "  ${PROXY_DOMAIN} → 10.2.10.1 added to OPNsense DNS."
else
    warn "  dns-manager failed — add the override manually in OPNsense:"
    warn "    Host: ${HPB_HOST_PART}   Domain: ${HPB_DOMAIN_PART}   IP: 10.2.10.1"
fi

echo ""
info "${GN}✓${CL} nextcloud-hpb installation completed successfully."
echo ""
info "  Signaling URL : wss://${PROXY_DOMAIN}/spreed"
info ""
info "  ${BOLD}ACTION REQUIRED — Public DNS record only:${CL}"
info "    ${PROXY_DOMAIN} → <WAN IP>  (external clients, e.g. 5G)"
info "    (Internal override already added to OPNsense above)"
