"""Authentik admin-API client for TAPPaaS (issue #45).

Drives a running Authentik instance over its REST API to idempotently
provision the per-consumer integration objects (Proxy Provider, Application,
embedded Outpost attachment) that the issue's manual checklist describes.

The token is the one created on first boot by ``AUTHENTIK_BOOTSTRAP_TOKEN``
(generated by ``identity.nix`` and passed to Authentik via EnvironmentFile);
``identity:install`` persists the same value into
``~/.authentik-credentials.txt`` (mode 600) on the cicd so this manager can
authenticate over the API.

Forward-auth verbs are implemented (Phase C — Open WebUI uses these).
OIDC verbs are scaffolded for the Phase D follow-up (Nextcloud).
"""

from __future__ import annotations

from dataclasses import dataclass

import httpx


# Authentik's default well-known slugs (created on first boot, never change).
DEFAULT_AUTHORIZATION_FLOW_SLUG = "default-provider-authorization-implicit-consent"
DEFAULT_INVALIDATION_FLOW_SLUG = "default-provider-invalidation-flow"
EMBEDDED_OUTPOST_NAME = "authentik Embedded Outpost"


@dataclass
class AuthentikConfig:
    """Connection settings for the Authentik admin API."""

    base_url: str               # e.g. "http://identity.mgmt.internal:9000"
    token: str
    verify_tls: bool = True
    timeout: float = 30.0

    @property
    def api(self) -> str:
        return f"{self.base_url.rstrip('/')}/api/v3"


@dataclass
class ProxyApp:
    """A forward-auth Authentik Application + Proxy Provider pair (Phase C)."""

    name: str                   # human-readable, used as Application name
    slug: str                   # URL slug (must match across runs for idempotency)
    external_host: str          # public URL of the protected service, e.g. https://openwebui.test.tapaas.org
    description: str = ""


@dataclass
class OidcApp:
    """An OIDC Application + Provider pair (Phase D — Nextcloud)."""

    name: str
    slug: str
    redirect_uris: list[str]
    scopes: list[str]


@dataclass
class ProxyAppResult:
    """Provider + application PKs returned after ensure."""

    application_pk: str         # core.Application primary key (UUID)
    provider_pk: int            # providers.proxy primary key (int)
    slug: str


class AuthentikManager:
    """Idempotent admin-API client for Authentik."""

    def __init__(self, config: AuthentikConfig):
        self.config = config
        self._client: httpx.Client | None = None
        # Per-instance flow-slug → pk cache (avoid sharing across managers).
        self._flow_cache: dict[str, str] = {}

    def connect(self) -> "AuthentikManager":
        self._client = httpx.Client(
            base_url=self.config.api,
            headers={
                "Authorization": f"Bearer {self.config.token}",
                "Accept": "application/json",
                "Content-Type": "application/json",
            },
            timeout=self.config.timeout,
            verify=self.config.verify_tls,
        )
        return self

    def disconnect(self):
        if self._client is not None:
            self._client.close()
        self._client = None

    def __enter__(self) -> "AuthentikManager":
        return self.connect()

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.disconnect()

    @property
    def client(self) -> httpx.Client:
        if not self._client:
            raise RuntimeError("Not connected. Use connect() or context manager.")
        return self._client

    # ── primitives ──────────────────────────────────────────────────────

    def _get_json(self, path: str, **params) -> dict:
        r = self.client.get(path, params=params)
        r.raise_for_status()
        return r.json()

    def _post_json(self, path: str, body: dict) -> dict:
        r = self.client.post(path, json=body)
        r.raise_for_status()
        return r.json()

    def _patch_json(self, path: str, body: dict) -> dict:
        r = self.client.patch(path, json=body)
        r.raise_for_status()
        return r.json()

    def _delete(self, path: str) -> None:
        r = self.client.delete(path)
        if r.status_code not in (200, 204, 404):
            r.raise_for_status()

    def test_connection(self) -> bool:
        """Hits a cheap, auth-required endpoint to confirm token validity."""
        try:
            self._get_json("/core/users/me/")
            return True
        except httpx.HTTPError:
            return False

    # ── search helpers (Authentik IGNORES the ?name=/?slug= URL filters and
    # returns the full list — every callsite MUST filter client-side or risk
    # PATCH-ing the wrong row) ───────────────────────────────────────────

    @staticmethod
    def _find_by_field(rows: list[dict], field: str, value) -> dict | None:
        for r in rows:
            if r.get(field) == value:
                return r
        return None

    @staticmethod
    def _find_by_name(rows: list[dict], name: str) -> dict | None:
        return AuthentikManager._find_by_field(rows, "name", name)

    # ── flow lookup (read-once cache) ───────────────────────────────────

    def _flow_pk(self, slug: str) -> str:
        if slug in self._flow_cache:
            return self._flow_cache[slug]
        results = self._get_json("/flows/instances/", slug=slug).get("results", [])
        if not results:
            raise RuntimeError(f"Authentik flow {slug!r} not found")
        self._flow_cache[slug] = results[0]["pk"]
        return self._flow_cache[slug]

    # ── Proxy / Forward-Auth (Phase C — Open WebUI) ─────────────────────

    def proxy_app_ensure(self, app: ProxyApp) -> ProxyAppResult:
        """Create or update a forward-auth Proxy Provider + Application.

        Idempotent: re-running with the same slug updates external_host in
        place. Returns the provider + application PKs (needed to attach to the
        outpost).
        """
        # Resolve the well-known authorization + invalidation flows.
        auth_flow_pk = self._flow_pk(DEFAULT_AUTHORIZATION_FLOW_SLUG)
        invalidation_flow_pk = self._flow_pk(DEFAULT_INVALIDATION_FLOW_SLUG)

        # Find or create the Proxy Provider.
        # NB: Authentik IGNORES the ?name= URL filter on /providers/proxy/ —
        # the server returns the full list regardless. We MUST filter
        # client-side; otherwise we'd PATCH whichever row is first in the
        # list and silently mangle unrelated providers (issue #45 PoC bug).
        provider_rows = self._get_json("/providers/proxy/").get("results", [])
        existing_provider = self._find_by_name(provider_rows, app.name)
        provider_body = {
            "name": app.name,
            "authorization_flow": auth_flow_pk,
            "invalidation_flow": invalidation_flow_pk,
            "external_host": app.external_host,
            "mode": "forward_single",
        }
        if existing_provider:
            provider_pk = existing_provider["pk"]
            self._patch_json(f"/providers/proxy/{provider_pk}/", provider_body)
        else:
            provider_pk = self._post_json("/providers/proxy/", provider_body)["pk"]

        # Find or create the Application — slug is the immutable key.
        # Same client-side filter (Authentik ignores ?slug= too). Also: an
        # Application has a 1:1 link to a Provider; if some OTHER app already
        # owns this provider_pk, reuse THAT app rather than POSTing a new one
        # (Authentik would 400 "Application with this provider already exists").
        app_rows = self._get_json("/core/applications/").get("results", [])
        existing_app = (
            self._find_by_field(app_rows, "slug", app.slug)
            or self._find_by_field(app_rows, "provider", provider_pk)
        )
        app_body = {
            "name": app.name,
            "slug": app.slug,
            "provider": provider_pk,
            "meta_description": app.description,
            "meta_launch_url": app.external_host,
        }
        if existing_app:
            application_pk = existing_app["pk"]
            # Authentik's /core/applications/<x>/ detail endpoint routes on
            # SLUG, not pk (lookup_field="slug" on the viewset). PATCH-by-pk
            # returns 404; PATCH-by-slug works.
            self._patch_json(f"/core/applications/{existing_app['slug']}/", app_body)
        else:
            application_pk = self._post_json("/core/applications/", app_body)["pk"]

        return ProxyAppResult(
            application_pk=application_pk,
            provider_pk=provider_pk,
            slug=app.slug,
        )

    def app_delete(self, slug: str) -> None:
        """Remove an Application and its Provider (proxy or oidc) by slug. Idempotent."""
        # Client-side filter — Authentik's ?slug= URL filter is ignored.
        all_apps = self._get_json("/core/applications/").get("results", [])
        match = self._find_by_field(all_apps, "slug", slug)
        apps = [match] if match else []
        for a in apps:
            provider_pk = a.get("provider")
            # Authentik routes /core/applications/<x>/ on SLUG, not pk.
            self._delete(f"/core/applications/{a['slug']}/")
            if provider_pk:
                # Try both endpoints; whichever matches deletes the provider.
                for endpoint in ("/providers/proxy", "/providers/oauth2"):
                    try:
                        self._delete(f"{endpoint}/{provider_pk}/")
                        break
                    except httpx.HTTPStatusError:
                        continue

    # ── Embedded Outpost ────────────────────────────────────────────────

    def _embedded_outpost(self) -> dict:
        # Client-side filter — Authentik's ?name= URL filter is ignored.
        all_outposts = self._get_json("/outposts/instances/").get("results", [])
        match = self._find_by_name(all_outposts, EMBEDDED_OUTPOST_NAME)
        if not match:
            raise RuntimeError(f"Authentik embedded outpost ({EMBEDDED_OUTPOST_NAME!r}) not found")
        return match

    def outpost_attach_provider(self, provider_pk: int) -> None:
        """Ensure the given provider PK is in the embedded outpost's providers list.

        Idempotent — patches in place if the provider isn't already attached.
        """
        outpost = self._embedded_outpost()
        providers = list(outpost.get("providers", []))
        if provider_pk in providers:
            return
        providers.append(provider_pk)
        self._patch_json(f"/outposts/instances/{outpost['pk']}/", {"providers": providers})

    def outpost_detach_provider(self, provider_pk: int) -> None:
        """Idempotent reverse of attach (used by accessControl/delete-service.sh)."""
        outpost = self._embedded_outpost()
        providers = [p for p in outpost.get("providers", []) if p != provider_pk]
        if len(providers) == len(outpost.get("providers", [])):
            return
        self._patch_json(f"/outposts/instances/{outpost['pk']}/", {"providers": providers})

    def outpost_set_authentik_host(self, authentik_host: str) -> None:
        """Set the embedded outpost's authentik_host (the identity public URL).

        Run once at identity install time (Phase B): tells the embedded outpost
        where to redirect users for the login UI. Without this, forward-auth
        flows redirect to the internal hostname which isn't reachable externally.
        """
        outpost = self._embedded_outpost()
        # `config` is a dict on Outpost; merge rather than replace so we keep
        # log_level / docker_network / kubernetes_replicas / etc.
        cfg = dict(outpost.get("config") or {})
        cfg["authentik_host"] = authentik_host
        self._patch_json(f"/outposts/instances/{outpost['pk']}/", {"config": cfg})

    # ── OIDC (Phase D — Nextcloud; scaffolded) ──────────────────────────

    def oidc_app_ensure(self, app: OidcApp) -> dict:  # pragma: no cover  (Phase D)
        """Create an OIDC Provider + Application; returns {client_id, client_secret, issuer}.

        Placeholder — wired in Phase D for Nextcloud. The real call hits
        ``/providers/oauth2/`` with client_type=confidential + the redirect URIs,
        then reads back the auto-generated client_id/secret.
        """
        raise NotImplementedError(
            "oidc_app_ensure is part of Phase D (deferred to follow-up); see plan in #45 comments"
        )
