# ============================================================================
# Docker Compose Configuration
# Project: Local AI Platform (OpenWebUI, SearxNG, LiteLLM, Postgres, n8n, Ollama, etc.)
# Author: Erik van Busschbach
# Last updated: 2025-08-13
# Version: 250813v11-STABLE
# Description:
#   - DRY environment variable management
#   - Secure DB initialization
#   - Correct bind mounts for Postgres & Redis
#   - Modular setup with health checks and explicit dependencies
#   - Cross-platform (macOS/Linux/WSL)
# ============================================================================

# version: "3.9"

networks:
  ai_network:

x-service-defaults: &defaults
  restart: unless-stopped
  networks:
    - ai_network
  env_file:
    - .env
    - .env.local
  healthcheck:
    interval: 30s
    timeout: 10s
    retries: 3

services:

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    environment:
      ENABLE_RAG_WEB_SEARCH: "true"
      RAG_WEB_SEARCH_ENGINE: searxng
      RAG_WEB_SEARCH_RESULT_COUNT: "3"
      SEARXNG_QUERY_URL: http://searxng:8080/search
    ports:
      - "${OPENWEBUI_PORT}:8080"
    volumes:
#      - ../data/open-webui/application_config:/app/config/admin:rw
#      - ../data/open-webui/functional_config:/app/config/user:rw
      - ../data/open-webui/user_data:/app/backend/data:rw
      - ../data/open-webui/logs:/app/backend/logs:rw
    depends_on:
      searxng:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:8080/health | jq -e '.status == true' || exit 1"]
      start_period: 60s
    <<: *defaults

  searxng:
    image: searxng/searxng:latest
    ports:
      - "${SEARXNG_PORT}:8080"
    environment:
      SEARXNG_BIND_ADDRESS: 0.0.0.0:8080
      SEARXNG_BASE_URL: "http://localhost:${SEARXNG_PORT}/"
      SEARXNG_LIMITER: "false"
    volumes:
      - ../data/searxng/application_config:/etc/searxng:rw
      # No functional_config mount defined currently for searxng
      - ../data/searxng/user_data:/var/lib/searxng:rw
      - ../data/searxng/logs:/var/log/searxng:rw
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8080 || exit 1"]
      start_period: 30s
    <<: *defaults

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_SUPERUSER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPERPASS}
      POSTGRES_DB: ${POSTGRES_DB}
      APP_DATABASES: ${APP_DATABASES}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ../data/postgres/application_config:/docker-entrypoint-initdb.d:rw
      - ../data/postgres/user_data:/var/lib/postgresql:rw
      - ../data/postgres/logs:/var/log/postgresql:rw
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U "$$POSTGRES_SUPERUSER" -d "$$POSTGRES_DB"']
      start_period: 60s
    <<: *defaults

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "${LITELLM_PORT}:4000"
    environment:
      LITELLM_DATABASE_URL: ${LITELLM_DATABASE_URL}
    volumes:
      - ../data/litellm/functional_config/config.yaml:/app/config.yaml:rw
      - ../data/litellm/user_data:/app/user_data:rw
      - ../data/litellm/logs:/app/logs:rw
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:4000/health/readiness | grep '\"status\":\"connected\"' || exit 1"]
      start_period: 60s
    <<: *defaults

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --appendonly yes
    volumes:
      - ../data/redis/user_data:/data:rw
      - ../data/redis/logs:/var/log/redis:rw
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    <<: *defaults
