services:
  litellm:
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:4000/health/readiness | grep '\"status\":\"connected\"' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

