services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "${LITELLM_PORT}:4000"
    environment:
      LITELLM_DATABASE_URL: ${LITELLM_DATABASE_URL}
    volumes:
      - ./litellm/admin_config:/app/config/admin:rw
      - ./litellm/user_config:/app/config/user:rw
      - ai_litellm_:/app/rw
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:4000/health/readiness || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
