# ============================================================================
# Docker Compose Configuration
# Project: Local AI Platform (OpenWebUI, Searxng, LiteLLM, Postgres)
# Author: Erik van Busschbach
# Last updated: 2025-08-11
# Version: 250811v7
# Description: This file defines the Docker services for the Local AI Platform,
#              including OpenWebUI, Searxng, LiteLLM, and Postgres
#              with secure database initialization and environment variable management.
#              Using DRY (Don't Repeat Yourself) principles for service definitions.
#              This configuration is designed for local development and testing.
#              It includes health checks, environment variable management,
#              and secure database initialization for multiple applications.
#              The configuration is modular and can be easily extended for additional services. In the .env file, you can define the applications and their database credentials.
# ============================================================================

volumes:
  open_webui_:
  searxng_:
  litellm_:
#  redis_:
  postgres_:

networks:
  ai_network:

x-service-defaults: &defaults
  restart: unless-stopped
  networks:
    - ai_network

services:

  # --- OpenWebUI frontend ---
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    environment:
      - ENABLE_RAG_WEB_SEARCH=true
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - SEARXNG_QUERY_URL=http://searxng:8080/search
    ports:
      - "${OPENWEBUI_PORT}:8080"
    volumes:
      - open_webui_:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - searxng
    <<: *defaults

  # --- Searxng search engine ---
  searxng:
    image: searxng/searxng:latest
    ports:
      - "${SEARXNG_PORT}:8080"
    volumes:
      - searxng_:/etc/searxng
    environment:
      - SEARXNG_BIND_ADDRESS=0.0.0.0:8080
      - SEARXNG_BASE_URL=http://localhost:${SEARXNG_PORT}/
      - SEARXNG_LIMITER=false
    <<: *defaults

  # --- PostgreSQL database ---
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_SUPERUSER}
      - POSTGRES_PASSWORD=${POSTGRES_SUPERPASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - APP_DATABASES=${APP_DATABASES}
    volumes:
      - postgres_:/var/lib/postgresql/data
      - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh:ro
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_SUPERUSER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    <<: *defaults

  # --- LiteLLM API ---
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "${LITELLM_PORT}:4000"
    environment:
      - LITELLM_DATABASE_URL=${LITELLM_DATABASE_URL:-}
      - LITELLM_CONFIG=/config/config.yaml
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - LITELLM_SALT_KEY=${LITELLM_SALT_KEY}
      - STORE_MODEL_IN_DB=${STORE_MODEL_IN_DB}
    volumes:
      - ./litellm_config:/config
      - litellm_:/app/data
      - ./get-db-url.sh:/get-db-url.sh:ro
    entrypoint: ["/bin/sh", "-c"]
    command: >
      export LITELLM_DATABASE_URL=$(/get-db-url.sh) &&
      echo "Using DB URL: $LITELLM_DATABASE_URL" &&
      exec /start
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    <<: *defaults

#  # --- Redis cache (optional) ---
#  redis:
#    image: redis:7-alpine
#    ports:
#      - "${REDIS_PORT}:6379"
#    command: redis-server --appendonly yes
#    volumes:
#      - ./redis:/data
#    <<: *defaults
