#!/usr/bin/env bash
#
# TAPPaaS logging VM update
#
# Update VM and apply module specific updates.
#
# Usage: ./update.sh <vmname>
# Example: ./update.sh logging
#

set -euo pipefail

. /home/tappaas/bin/common-install-routines.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

VMNAME="$(get_config_value 'vmname' "$1")"
VMID="$(get_config_value 'vmid')"
NODE="$(get_config_value 'node' "$(get_node_hostname 0)")"
ZONE0NAME="$(get_config_value 'zone0' 'mgmt')"
# Resolve HA node: on a single-node cluster get_default_ha_node returns empty,
# and get_config_value aborts when both key-missing AND default-empty. Pass a
# non-empty placeholder so the banner is optional rather than fatal.
HANODE_DEFAULT="$(get_default_ha_node "$NODE")"
HANODE="$(get_config_value 'HANode' "${HANODE_DEFAULT:-NONE}")"

echo ""
info "${BOLD}Post-Install Configuration${CL}"
info "  VM: ${VMNAME} (VMID: ${VMID})"

echo ""
info "${BOLD}Installation Complete${CL}"
info "  VM: ${VMNAME} (VMID: ${VMID})"
info "  Node: ${NODE}"
info "  Zone: ${ZONE0NAME}"
if [[ -n "${HANODE}" && "${HANODE}" != "NONE" ]]; then
    info "  HA Node: ${HANODE}"
fi

# ── Configure OPNsense to forward syslog to this VM ──────────────────
# Idempotent: matches the destination by description ("tappaas-logging").
# Skipped when firewallType != opnsense (deployment uses a different firewall).
echo ""
info "${BOLD}Configure OPNsense syslog forwarding${CL}"

FIREWALL_TYPE="$(get_config_value 'firewallType' 'opnsense')"
SYSLOG_TARGET="${VMNAME}.${ZONE0NAME}.internal"
SYSLOG_DESC="tappaas-logging"

if [[ "${FIREWALL_TYPE}" != "opnsense" ]]; then
    info "  firewallType=${FIREWALL_TYPE} — skipping (configure manually on your firewall)"
elif ! command -v syslog-manager >/dev/null 2>&1; then
    warn "  syslog-manager CLI not found — rebuild the mothership to pick it up"
    warn "  Manual fallback: System → Settings → Logging / Targets → add ${SYSLOG_TARGET}:1514 (TCP, RFC 5424)"
else
    info "  Target: ${SYSLOG_TARGET}:1514 (TCP, RFC 5424)"
    if syslog-manager add-destination \
            --hostname "${SYSLOG_TARGET}" \
            --port 1514 \
            --transport tcp4 \
            --rfc5424 \
            --description "${SYSLOG_DESC}" \
            --no-ssl-verify; then
        if syslog-manager reconfigure --no-ssl-verify; then
            info "  ${GN}✓${CL} OPNsense will now forward syslog to ${SYSLOG_TARGET}:1514"
        else
            warn "  Destination saved but OPNsense reconfigure failed — apply manually in the UI"
        fi
    else
        warn "  Could not add OPNsense syslog destination — configure manually via the UI"
    fi
fi

# ── Configure Proxmox nodes to forward rsyslog to this VM ────────────
# Each cluster node ships its journal-forwarded syslog (via rsyslog) to the
# Promtail syslog receiver on tcp/1515 (source=proxmox).
# Idempotent: scp overwrites the conf file; rsyslog restart is harmless.
echo ""
info "${BOLD}Configure Proxmox nodes' rsyslog forwarding${CL}"

CONFIG_FILE="/home/tappaas/config/configuration.json"
NODE_COUNT="$(jq -r '."tappaas-nodes" | length' "${CONFIG_FILE}" 2>/dev/null || echo 0)"

if [[ "${NODE_COUNT}" -lt 1 ]]; then
    warn "  No tappaas-nodes in configuration.json — skipping"
else
    SYSLOG_FQDN="${VMNAME}.${ZONE0NAME}.internal"

    # Generate the rsyslog snippet once, then scp it to each node.
    TMP_CONF="$(mktemp)"
    trap 'rm -f "${TMP_CONF}"' EXIT
    cat > "${TMP_CONF}" <<EOF
# TAPPaaS-managed — ship syslog to Loki via Promtail on ${SYSLOG_FQDN}:1515
# Format: RFC 5424 over TCP with octet-counted framing (RFC 5425)
# Do not edit by hand; this file is regenerated by logging/update.sh.
*.* action(type="omfwd"
           target="${SYSLOG_FQDN}"
           port="1515"
           protocol="tcp"
           template="RSYSLOG_SyslogProtocol23Format"
           TCP_Framing="octet-counted"
           Action.ResumeRetryCount="-1"
           queue.type="LinkedList"
           queue.size="10000")
EOF

    SSH_OPTS="-o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=accept-new"
    REMOTE_PATH="/etc/rsyslog.d/99-tappaas-loki.conf"

    for i in $(seq 0 $((NODE_COUNT - 1))); do
        NODE_HOSTNAME="$(jq -r ".\"tappaas-nodes\"[${i}].hostname" "${CONFIG_FILE}")"
        NODE_FQDN="${NODE_HOSTNAME}.mgmt.internal"
        info "  → ${NODE_HOSTNAME}"

        # PVE 9 / Debian 13 (trixie) ships journald-only by default — install
        # rsyslog if missing. Its default config wires `imjournal` so all
        # journal entries flow through, then our 99-tappaas-loki.conf adds
        # the omfwd forwarder to Promtail. Idempotent.
        # shellcheck disable=SC2086
        if ! ssh ${SSH_OPTS} "root@${NODE_FQDN}" "command -v rsyslogd >/dev/null" 2>/dev/null; then
            info "    installing rsyslog..."
            # shellcheck disable=SC2086
            if ! ssh ${SSH_OPTS} "root@${NODE_FQDN}" \
                "DEBIAN_FRONTEND=noninteractive apt-get install -y -qq rsyslog >/dev/null 2>&1"; then
                warn "    ${NODE_HOSTNAME}: rsyslog install failed — skipping"
                continue
            fi
        fi

        # shellcheck disable=SC2086
        if ! scp ${SSH_OPTS} "${TMP_CONF}" "root@${NODE_FQDN}:${REMOTE_PATH}" >/dev/null 2>&1; then
            warn "    ${NODE_HOSTNAME}: scp failed — node unreachable or no SSH key"
            continue
        fi

        # shellcheck disable=SC2086
        if ssh ${SSH_OPTS} "root@${NODE_FQDN}" \
            "systemctl enable --now rsyslog >/dev/null 2>&1 && systemctl restart rsyslog" 2>/dev/null; then
            info "    ${GN}✓${CL} ${NODE_HOSTNAME}: rsyslog → ${SYSLOG_FQDN}:1515"
        else
            warn "    ${NODE_HOSTNAME}: config pushed but rsyslog (enable|restart) failed"
        fi
    done
fi

echo ""
info "${BOLD}Next steps${CL}"
info "  - Retrieve the initial Grafana admin password:"
info "      ssh tappaas@${VMNAME}.${ZONE0NAME}.internal -- sudo cat /root/grafana-admin-password.initial"
info "      Then change it in the UI and:"
info "      ssh tappaas@${VMNAME}.${ZONE0NAME}.internal -- sudo rm /root/grafana-admin-password.initial"
info "  - Other VMs: install a Promtail client pointing at http://${VMNAME}.${ZONE0NAME}.internal:3100"
