#!/usr/bin/env bash
#
# TAPPaaS Nextcloud Service - Install
#
# Verifies the Nextcloud VM is reachable before dependent modules install.
#
# Usage: install-service.sh <module-name>
#

set -euo pipefail

. /home/tappaas/bin/common-install-routines.sh

MODULE="${1:-}"
readonly CONFIG_DIR="/home/tappaas/config"
readonly NEXTCLOUD_JSON="${CONFIG_DIR}/nextcloud.json"

VMNAME=$(jq -r '.vmname' "${NEXTCLOUD_JSON}")
ZONE=$(jq -r '.zone0' "${NEXTCLOUD_JSON}")
INTERNAL_URL="http://${VMNAME}.${ZONE}.internal"

info "nextcloud:nextcloud install-service — verifying Nextcloud is reachable for module: ${MODULE}"

if curl -sf --max-time 10 "${INTERNAL_URL}/status.php" | grep -q '"installed":true'; then
    info "${GN}✓${CL} Nextcloud is installed and reachable at ${INTERNAL_URL}"
else
    die "Nextcloud is not responding at ${INTERNAL_URL}/status.php — ensure the nextcloud module is fully installed"
fi

# ── Connector wiring (ADR-COM-0002) — declarative, provider-owned ──────────────
# A consumer that wants the OnlyOffice editor DECLARES it in its own manifest, under the
# dependency capability:  config["nextcloud:nextcloud"].connector == "onlyoffice".
# Nextcloud (the provider) then owns the wiring:
#   - URLs are DERIVED from the consumer manifest (SSOT) — no readFile, no hardcoding.
#   - the JWT secret is OWNED by the consumer (euro-office auto-generates it in nix on first
#     boot); we READ it once — the single runtime cross-VM step.
#   - we write the 4-var contract to /etc/secrets/onlyoffice.env on the Nextcloud VM; the
#     declarative nextcloud-configure-eurooffice.service applies it idempotently via occ.
# Generic: any onlyoffice consumer reuses this; non-declaring consumers are a no-op.
CONSUMER_JSON="${CONFIG_DIR}/${MODULE}.json"
CONNECTOR=""
# Read 'connector' from EITHER the raw manifest (nested under the dependency
# capability) OR the flattened on-disk canonical form (#207): install-module
# renders the consumer JSON to canonical Pattern A, which hoists the
# config["nextcloud:nextcloud"].connector field to top-level. Checking both
# keeps this generic installer correct regardless of which form it's handed.
[[ -n "${MODULE}" && -f "${CONSUMER_JSON}" ]] && \
    CONNECTOR=$(jq -r '.config["nextcloud:nextcloud"].connector // .connector // empty' "${CONSUMER_JSON}" 2>/dev/null || true)

if [[ "${CONNECTOR}" == "onlyoffice" ]]; then
    info "  ${MODULE} declares an onlyoffice connector — wiring it (ADR-COM-0002)"

    EO_VMNAME=$(jq -r '.vmname' "${CONSUMER_JSON}")
    EO_ZONE=$(jq -r '.zone0' "${CONSUMER_JSON}")
    TAPPAAS_DOMAIN=$(jq -r '.tappaas.domain // empty' "${CONFIG_DIR}/configuration.json" 2>/dev/null || true)
    EO_HOST="${EO_VMNAME}.${EO_ZONE}.internal"
    NC_HOST="${VMNAME}.${ZONE}.internal"

    # URLs — derived from manifests, never hardcoded
    EURO_OFFICE_URL="https://${EO_VMNAME}.${TAPPAAS_DOMAIN}"
    EURO_OFFICE_INTERNAL_URL="http://${EO_HOST}/"
    NEXTCLOUD_PUBLIC_URL="${VMNAME}.${TAPPAAS_DOMAIN}"

    # JWT — owned + generated by euro-office (nix, first boot). Read once.
    JWT_SECRET=$(ssh -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=accept-new \
        "tappaas@${EO_HOST}" \
        "sudo grep -h '^JWT_SECRET=' /etc/secrets/euro-office.env 2>/dev/null | cut -d= -f2-" 2>/dev/null || true)

    if [[ -z "${JWT_SECRET}" ]]; then
        warn "  euro-office JWT not available yet on ${EO_HOST} — connector left unconfigured; it will wire on the next nextcloud sync once euro-office has booted."
    else
        # Write the 4-var contract on the Nextcloud VM; the idempotent
        # nextcloud-configure-eurooffice.service applies it via occ.
        if printf 'JWT_SECRET=%s\nEURO_OFFICE_URL=%s\nEURO_OFFICE_INTERNAL_URL=%s\nNEXTCLOUD_PUBLIC_URL=%s\n' \
                "${JWT_SECRET}" "${EURO_OFFICE_URL}" "${EURO_OFFICE_INTERNAL_URL}" "${NEXTCLOUD_PUBLIC_URL}" \
            | ssh -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=accept-new \
                "tappaas@${NC_HOST}" \
                "sudo install -m600 -o root -g root /dev/stdin /etc/secrets/onlyoffice.env && \
                 sudo systemctl restart nextcloud-configure-eurooffice.service"
        then
            info "${GN}✓${CL} onlyoffice connector wired for ${MODULE}"
        else
            warn "  failed to apply onlyoffice.env on ${NC_HOST} — re-run after both VMs are up"
        fi
    fi
fi
