# Site settings
title: TAPPaaS
author:
  name: Lars Rossen
  email: lars@hrossen.dk
description: "TAPPaaS Documentation Site."

# Build settings
remote_theme: pages-themes/architect@v0.2.0
show_downloads: false