# Copyright (c) 2026 TAPPaaS org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# ============================================================================
# TAPPaaS - Satellite (external host)
# ============================================================================
# Version: 0.1.0  (ADR-010 implementation P1 — SKELETON, not yet functional)
# Author: @larsrossen (TAPPaaS)
#
# Deployed onto an EXTERNAL host (a VPS or any machine with a public IP) by
# `satellite-manager` via nixos-anywhere — NOT a Proxmox VM. The concrete
# per-deployment values (roles, ports, peer keys, addresses, S3 settings) are
# generated from ~/config/satellite-<name>.json by satellite-manager and written
# to ./satellite-settings.nix, imported below. This file is the ROLE-GATED
# skeleton; the heavy logic lands in packages P2–P6 (see the implementation
# tracker). TODO markers below mark per-package work.
#
# Trust stance (ADR-010 §1, §7): blind relay + blind vault. The host holds no
# plaintext and no cluster-held credential; management is one-directional (the
# home/tunnel side can never reach this host's SSH or PBS-admin).
# ============================================================================

{ config, lib, pkgs, modulesPath, ... }:

let
  # --- generated by satellite-manager from satellite.json (placeholders here) ---
  cfg = {
    roles            = [ ];          # subset of [ "reverse-proxy" "admin-vpn" "backup" ]
    tunnel = {
      satelliteAddr  = "10.255.0.0"; # /31 link, satellite end
      homeAddr       = "10.255.0.1"; # /31 link, home (OPNsense) end
      wgPort         = 51820;        # public UDP listener for the infra tunnel
    };
    homeCaddyAddr    = "10.255.0.1"; # reverse-proxy: forward target (Caddy on OPNsense over the tunnel)
    adminWgPort      = 51821;        # admin-vpn: public UDP relay port
    homeAdminWgAddr  = "10.255.0.1"; # admin-vpn: OPNsense admin-WG listener (over the tunnel)
  };
  hasRole = r: lib.elem r cfg.roles;
in
{
  imports = [
    /etc/nixos/hardware-configuration.nix
    # ./satellite-settings.nix   # generated per-deployment; uncomment once P3 writes it
  ];

  # ==========================================================================
  # BASE
  # ==========================================================================
  boot.loader.grub.enable = true;
  networking.hostName = lib.mkDefault "satellite";
  time.timeZone = lib.mkDefault "UTC";

  # ==========================================================================
  # SSH — operator out-of-band key only; key auth only; no cluster-held key
  # (ADR-010 §7.3 rule 1/2). The provisioning credential is revoked post-install.
  # ==========================================================================
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = false;
    settings.PermitRootLogin = "prohibit-password";
  };
  # TODO[P3]: authorizedKeys = the operator out-of-band key (NOT a tappaas-cicd key).

  # ==========================================================================
  # HOST FIREWALL — one-directional management (ADR-010 §7.3 rule 4)
  # The home/tunnel side must NOT reach this host's SSH (22) or PBS-admin (8007).
  # Public: 443/tcp + 80/tcp (reverse-proxy), wgPort/udp (tunnel), adminWgPort/udp
  # (admin-vpn). Opened per active role below.
  # ==========================================================================
  networking.firewall = {
    enable = true;
    allowedTCPPorts = lib.optionals (hasRole "reverse-proxy") [ 443 80 ];
    allowedUDPPorts =
      [ cfg.tunnel.wgPort ]
      ++ lib.optionals (hasRole "admin-vpn") [ cfg.adminWgPort ];
    # TODO[P7]: explicitly DROP the tunnel interface -> {22,8007}; allow SSH only
    # from the operator's out-of-band source.
  };

  # ==========================================================================
  # WireGuard INFRA TUNNEL — satellite LISTENS; home dials out (ADR-010 §4)
  # ==========================================================================
  networking.wireguard.interfaces.wg-infra = {
    listenPort = cfg.tunnel.wgPort;
    ips = [ "${cfg.tunnel.satelliteAddr}/31" ];
    # privateKeyFile generated on-host at first boot (never leaves the host).
    # TODO[P2]: privateKeyFile = "/etc/wireguard/wg-infra.key";
    # TODO[P2]: peers = [ { publicKey = <home OPNsense pubkey>;
    #                       allowedIPs = [ "${cfg.tunnel.homeAddr}/32" ]; } ];
    # NOTE: no Endpoint for the home peer — it dials in; the satellite learns it
    # from the handshake (roaming). Keepalive lives on the HOME side.
  };

  # ==========================================================================
  # ROLE: reverse-proxy — nginx `stream` L4 passthrough + PROXY protocol v2
  # (ADR-010 §2, §5.8). All :443 -> Caddy-on-OPNsense over the tunnel; :80 too
  # (Caddy issues the redirect). The satellite NEVER terminates TLS.
  # ==========================================================================
  services.nginx = lib.mkIf (hasRole "reverse-proxy") {
    enable = true;
    # TODO[P4]: streamConfig — listen 443/80; proxy_pass ${cfg.homeCaddyAddr}:{443,80};
    #           proxy_protocol on;  (Caddy at home must trust PROXY v2 — preserves client IP
    #           for ADR-005 zone ACLs). ssl_preread only needed for a future multi-site satellite.
  };

  # ==========================================================================
  # ROLE: admin-vpn — BLIND UDP relay of an admin WireGuard session that
  # terminates on OPNsense (ADR-010 §6). The satellite holds no admin keys.
  # adminWgPort/udp  ->  ${cfg.homeAdminWgAddr}:adminWgPort  over the infra tunnel.
  # ==========================================================================
  # TODO[P5]: stateful UDP DNAT/forward (nftables) adminWgPort -> home admin-WG
  #           listener; admin-side MTU 1340 for the double-encapsulated path.

  # ==========================================================================
  # ROLE: backup — off-site PBS, PULL model; S3 Object-Lock backend by default
  # (ADR-010 §3). Stores ciphertext only (client-side encrypted at home).
  # ==========================================================================
  # TODO[P6]: proxmox-backup-server; datastore on S3 (Object Lock) or a ZFS volume;
  #           register home PBS as a pull remote (--remove-vanished false, read-only
  #           token); reuse the #228 verify/prune schedule; tune Object-Lock retention
  #           vs. prune/GC.

  # ==========================================================================
  # UPDATES — pull-based, signed (ADR-010 §7.3 rule 3). The cluster never pushes.
  # ==========================================================================
  # TODO[P3]: system.autoUpgrade from the pinned/signed update.ref.

  system.stateVersion = "25.05";
}
